package CobroCoactivo.Persistencia;
// Generated 10/08/2018 01:53:59 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * CivActosAdministractivos generated by hbm2java
 */
public class CivActosAdministractivos  implements java.io.Serializable {


     private BigDecimal actId;
     private CivUsuarios civUsuarios;
     private String actNumero;
     private String actFecha;

    public CivActosAdministractivos() {
    }

	
    public CivActosAdministractivos(BigDecimal actId, CivUsuarios civUsuarios) {
        this.actId = actId;
        this.civUsuarios = civUsuarios;
    }
    public CivActosAdministractivos(BigDecimal actId, CivUsuarios civUsuarios, String actNumero, String actFecha) {
       this.actId = actId;
       this.civUsuarios = civUsuarios;
       this.actNumero = actNumero;
       this.actFecha = actFecha;
    }
   
    public BigDecimal getActId() {
        return this.actId;
    }
    
    public void setActId(BigDecimal actId) {
        this.actId = actId;
    }
    public CivUsuarios getCivUsuarios() {
        return this.civUsuarios;
    }
    
    public void setCivUsuarios(CivUsuarios civUsuarios) {
        this.civUsuarios = civUsuarios;
    }
    public String getActNumero() {
        return this.actNumero;
    }
    
    public void setActNumero(String actNumero) {
        this.actNumero = actNumero;
    }
    public String getActFecha() {
        return this.actFecha;
    }
    
    public void setActFecha(String actFecha) {
        this.actFecha = actFecha;
    }




}


