package CobroCoactivo.Persistencia;
// Generated 30/05/2018 02:43:14 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * CivConceptos generated by hbm2java
 */
public class CivConceptos  implements java.io.Serializable {


     private BigDecimal conId;
     private CivTipoConceptos civTipoConceptos;
     private CivEstadoConceptos civEstadoConceptos;
     private String conDescripcion;
     private Date conFechaproceso;
     private Set civDetalleDeudases = new HashSet(0);

    public CivConceptos() {
    }

	
    public CivConceptos(BigDecimal conId, CivTipoConceptos civTipoConceptos, CivEstadoConceptos civEstadoConceptos, String conDescripcion) {
        this.conId = conId;
        this.civTipoConceptos = civTipoConceptos;
        this.civEstadoConceptos = civEstadoConceptos;
        this.conDescripcion = conDescripcion;
    }
    public CivConceptos(BigDecimal conId, CivTipoConceptos civTipoConceptos, CivEstadoConceptos civEstadoConceptos, String conDescripcion, Date conFechaproceso, Set civDetalleDeudases) {
       this.conId = conId;
       this.civTipoConceptos = civTipoConceptos;
       this.civEstadoConceptos = civEstadoConceptos;
       this.conDescripcion = conDescripcion;
       this.conFechaproceso = conFechaproceso;
       this.civDetalleDeudases = civDetalleDeudases;
    }
   
    public BigDecimal getConId() {
        return this.conId;
    }
    
    public void setConId(BigDecimal conId) {
        this.conId = conId;
    }
    public CivTipoConceptos getCivTipoConceptos() {
        return this.civTipoConceptos;
    }
    
    public void setCivTipoConceptos(CivTipoConceptos civTipoConceptos) {
        this.civTipoConceptos = civTipoConceptos;
    }
    public CivEstadoConceptos getCivEstadoConceptos() {
        return this.civEstadoConceptos;
    }
    
    public void setCivEstadoConceptos(CivEstadoConceptos civEstadoConceptos) {
        this.civEstadoConceptos = civEstadoConceptos;
    }
    public String getConDescripcion() {
        return this.conDescripcion;
    }
    
    public void setConDescripcion(String conDescripcion) {
        this.conDescripcion = conDescripcion;
    }
    public Date getConFechaproceso() {
        return this.conFechaproceso;
    }
    
    public void setConFechaproceso(Date conFechaproceso) {
        this.conFechaproceso = conFechaproceso;
    }
    public Set getCivDetalleDeudases() {
        return this.civDetalleDeudases;
    }
    
    public void setCivDetalleDeudases(Set civDetalleDeudases) {
        this.civDetalleDeudases = civDetalleDeudases;
    }




}


