package CobroCoactivo.Persistencia;
// Generated 28/06/2018 06:29:52 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * CivDetalleDeudas generated by hbm2java
 */
public class CivDetalleDeudas  implements java.io.Serializable {


     private BigDecimal detdeuId;
     private CivDeudas civDeudas;
     private CivConceptos civConceptos;
     private CivEstadoDetalleDeudas civEstadoDetalleDeudas;
     private BigDecimal deuValor;
     private Date deuFechaproceso;

    public CivDetalleDeudas() {
    }

	
    public CivDetalleDeudas(BigDecimal detdeuId, CivDeudas civDeudas, CivConceptos civConceptos, CivEstadoDetalleDeudas civEstadoDetalleDeudas) {
        this.detdeuId = detdeuId;
        this.civDeudas = civDeudas;
        this.civConceptos = civConceptos;
        this.civEstadoDetalleDeudas = civEstadoDetalleDeudas;
    }
    public CivDetalleDeudas(BigDecimal detdeuId, CivDeudas civDeudas, CivConceptos civConceptos, CivEstadoDetalleDeudas civEstadoDetalleDeudas, BigDecimal deuValor, Date deuFechaproceso) {
       this.detdeuId = detdeuId;
       this.civDeudas = civDeudas;
       this.civConceptos = civConceptos;
       this.civEstadoDetalleDeudas = civEstadoDetalleDeudas;
       this.deuValor = deuValor;
       this.deuFechaproceso = deuFechaproceso;
    }
   
    public BigDecimal getDetdeuId() {
        return this.detdeuId;
    }
    
    public void setDetdeuId(BigDecimal detdeuId) {
        this.detdeuId = detdeuId;
    }
    public CivDeudas getCivDeudas() {
        return this.civDeudas;
    }
    
    public void setCivDeudas(CivDeudas civDeudas) {
        this.civDeudas = civDeudas;
    }
    public CivConceptos getCivConceptos() {
        return this.civConceptos;
    }
    
    public void setCivConceptos(CivConceptos civConceptos) {
        this.civConceptos = civConceptos;
    }
    public CivEstadoDetalleDeudas getCivEstadoDetalleDeudas() {
        return this.civEstadoDetalleDeudas;
    }
    
    public void setCivEstadoDetalleDeudas(CivEstadoDetalleDeudas civEstadoDetalleDeudas) {
        this.civEstadoDetalleDeudas = civEstadoDetalleDeudas;
    }
    public BigDecimal getDeuValor() {
        return this.deuValor;
    }
    
    public void setDeuValor(BigDecimal deuValor) {
        this.deuValor = deuValor;
    }
    public Date getDeuFechaproceso() {
        return this.deuFechaproceso;
    }
    
    public void setDeuFechaproceso(Date deuFechaproceso) {
        this.deuFechaproceso = deuFechaproceso;
    }




}


