package CobroCoactivo.Persistencia;
// Generated 27/07/2018 01:43:20 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * CivDetalleExpedientes generated by hbm2java
 */
public class CivDetalleExpedientes  implements java.io.Serializable {


     private BigDecimal detexpId;
     private CivTipoDetalleExpedientes civTipoDetalleExpedientes;
     private CivExpedientes civExpedientes;
     private CivEstadoDetalleExpedientes civEstadoDetalleExpedientes;
     private String detexpDescripcion;
     private Date detexpFechaproceso;
     private Set civArchivoDetExpedienteses = new HashSet(0);

    public CivDetalleExpedientes() {
    }

	
    public CivDetalleExpedientes(BigDecimal detexpId, CivTipoDetalleExpedientes civTipoDetalleExpedientes, CivExpedientes civExpedientes, CivEstadoDetalleExpedientes civEstadoDetalleExpedientes, String detexpDescripcion) {
        this.detexpId = detexpId;
        this.civTipoDetalleExpedientes = civTipoDetalleExpedientes;
        this.civExpedientes = civExpedientes;
        this.civEstadoDetalleExpedientes = civEstadoDetalleExpedientes;
        this.detexpDescripcion = detexpDescripcion;
    }
    public CivDetalleExpedientes(BigDecimal detexpId, CivTipoDetalleExpedientes civTipoDetalleExpedientes, CivExpedientes civExpedientes, CivEstadoDetalleExpedientes civEstadoDetalleExpedientes, String detexpDescripcion, Date detexpFechaproceso, Set civArchivoDetExpedienteses) {
       this.detexpId = detexpId;
       this.civTipoDetalleExpedientes = civTipoDetalleExpedientes;
       this.civExpedientes = civExpedientes;
       this.civEstadoDetalleExpedientes = civEstadoDetalleExpedientes;
       this.detexpDescripcion = detexpDescripcion;
       this.detexpFechaproceso = detexpFechaproceso;
       this.civArchivoDetExpedienteses = civArchivoDetExpedienteses;
    }
   
    public BigDecimal getDetexpId() {
        return this.detexpId;
    }
    
    public void setDetexpId(BigDecimal detexpId) {
        this.detexpId = detexpId;
    }
    public CivTipoDetalleExpedientes getCivTipoDetalleExpedientes() {
        return this.civTipoDetalleExpedientes;
    }
    
    public void setCivTipoDetalleExpedientes(CivTipoDetalleExpedientes civTipoDetalleExpedientes) {
        this.civTipoDetalleExpedientes = civTipoDetalleExpedientes;
    }
    public CivExpedientes getCivExpedientes() {
        return this.civExpedientes;
    }
    
    public void setCivExpedientes(CivExpedientes civExpedientes) {
        this.civExpedientes = civExpedientes;
    }
    public CivEstadoDetalleExpedientes getCivEstadoDetalleExpedientes() {
        return this.civEstadoDetalleExpedientes;
    }
    
    public void setCivEstadoDetalleExpedientes(CivEstadoDetalleExpedientes civEstadoDetalleExpedientes) {
        this.civEstadoDetalleExpedientes = civEstadoDetalleExpedientes;
    }
    public String getDetexpDescripcion() {
        return this.detexpDescripcion;
    }
    
    public void setDetexpDescripcion(String detexpDescripcion) {
        this.detexpDescripcion = detexpDescripcion;
    }
    public Date getDetexpFechaproceso() {
        return this.detexpFechaproceso;
    }
    
    public void setDetexpFechaproceso(Date detexpFechaproceso) {
        this.detexpFechaproceso = detexpFechaproceso;
    }
    public Set getCivArchivoDetExpedienteses() {
        return this.civArchivoDetExpedienteses;
    }
    
    public void setCivArchivoDetExpedienteses(Set civArchivoDetExpedienteses) {
        this.civArchivoDetExpedienteses = civArchivoDetExpedienteses;
    }




}


