package CobroCoactivo.Persistencia;
// Generated 28/06/2018 06:29:52 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * CivDatosPersonas generated by hbm2java
 */
public class CivDatosPersonas  implements java.io.Serializable {


     private BigDecimal datperId;
     private CivPersonas civPersonas;
     private CivEstadoDatosPersonas civEstadoDatosPersonas;
     private CivTipoDatosPersonas civTipoDatosPersonas;
     private String datperDescripcion;
     private Date datperFechaproceso;

    public CivDatosPersonas() {
    }

	
    public CivDatosPersonas(BigDecimal datperId, CivPersonas civPersonas, CivEstadoDatosPersonas civEstadoDatosPersonas, CivTipoDatosPersonas civTipoDatosPersonas, String datperDescripcion) {
        this.datperId = datperId;
        this.civPersonas = civPersonas;
        this.civEstadoDatosPersonas = civEstadoDatosPersonas;
        this.civTipoDatosPersonas = civTipoDatosPersonas;
        this.datperDescripcion = datperDescripcion;
    }
    public CivDatosPersonas(BigDecimal datperId, CivPersonas civPersonas, CivEstadoDatosPersonas civEstadoDatosPersonas, CivTipoDatosPersonas civTipoDatosPersonas, String datperDescripcion, Date datperFechaproceso) {
       this.datperId = datperId;
       this.civPersonas = civPersonas;
       this.civEstadoDatosPersonas = civEstadoDatosPersonas;
       this.civTipoDatosPersonas = civTipoDatosPersonas;
       this.datperDescripcion = datperDescripcion;
       this.datperFechaproceso = datperFechaproceso;
    }
   
    public BigDecimal getDatperId() {
        return this.datperId;
    }
    
    public void setDatperId(BigDecimal datperId) {
        this.datperId = datperId;
    }
    public CivPersonas getCivPersonas() {
        return this.civPersonas;
    }
    
    public void setCivPersonas(CivPersonas civPersonas) {
        this.civPersonas = civPersonas;
    }
    public CivEstadoDatosPersonas getCivEstadoDatosPersonas() {
        return this.civEstadoDatosPersonas;
    }
    
    public void setCivEstadoDatosPersonas(CivEstadoDatosPersonas civEstadoDatosPersonas) {
        this.civEstadoDatosPersonas = civEstadoDatosPersonas;
    }
    public CivTipoDatosPersonas getCivTipoDatosPersonas() {
        return this.civTipoDatosPersonas;
    }
    
    public void setCivTipoDatosPersonas(CivTipoDatosPersonas civTipoDatosPersonas) {
        this.civTipoDatosPersonas = civTipoDatosPersonas;
    }
    public String getDatperDescripcion() {
        return this.datperDescripcion;
    }
    
    public void setDatperDescripcion(String datperDescripcion) {
        this.datperDescripcion = datperDescripcion;
    }
    public Date getDatperFechaproceso() {
        return this.datperFechaproceso;
    }
    
    public void setDatperFechaproceso(Date datperFechaproceso) {
        this.datperFechaproceso = datperFechaproceso;
    }




}


