package CobroCoactivo.Persistencia;
// Generated 27/07/2018 01:43:20 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * CivDeudasImpuesto generated by hbm2java
 */
public class CivDeudasImpuesto  implements java.io.Serializable {


     private BigDecimal deuimpId;
     private String deuimpConsecutivo;
     private String deuimpFecha;
     private String deuimpTipo;
     private String deuimpValor;
     private String deuimpMotivo;
     private String deuimpReferencia;
     private String deuimpNombre1;
     private String deuimpNombre2;
     private String deuimpApellido1;
     private String deuimpApellido2;
     private String deuimpTipodocumento;
     private String deuimpDocumento;
     private String deuimpSexo;
     private String deuimpDireccion1;
     private String deuimpDireccion2;
     private String deuimpCelular;
     private String deuimpTelefono;
     private String deuimpCorreoelectronico;
     private String deuimpPlaca;
     private String deuimpServiciovehiculo;
     private String deuimpClasevehiculo;
     private String deuimpAvaluo;
     private String deuimpLiquidacionoficial;
     private String deuimpFechaliquidacion;
     private String deuimpFechamatricula;
     private BigDecimal deuimpArchivoFk;

    public CivDeudasImpuesto() {
    }

	
    public CivDeudasImpuesto(BigDecimal deuimpId) {
        this.deuimpId = deuimpId;
    }
    public CivDeudasImpuesto(BigDecimal deuimpId, String deuimpConsecutivo, String deuimpFecha, String deuimpTipo, String deuimpValor, String deuimpMotivo, String deuimpReferencia, String deuimpNombre1, String deuimpNombre2, String deuimpApellido1, String deuimpApellido2, String deuimpTipodocumento, String deuimpDocumento, String deuimpSexo, String deuimpDireccion1, String deuimpDireccion2, String deuimpCelular, String deuimpTelefono, String deuimpCorreoelectronico, String deuimpPlaca, String deuimpServiciovehiculo, String deuimpClasevehiculo, String deuimpAvaluo, String deuimpLiquidacionoficial, String deuimpFechaliquidacion, String deuimpFechamatricula, BigDecimal deuimpArchivoFk) {
       this.deuimpId = deuimpId;
       this.deuimpConsecutivo = deuimpConsecutivo;
       this.deuimpFecha = deuimpFecha;
       this.deuimpTipo = deuimpTipo;
       this.deuimpValor = deuimpValor;
       this.deuimpMotivo = deuimpMotivo;
       this.deuimpReferencia = deuimpReferencia;
       this.deuimpNombre1 = deuimpNombre1;
       this.deuimpNombre2 = deuimpNombre2;
       this.deuimpApellido1 = deuimpApellido1;
       this.deuimpApellido2 = deuimpApellido2;
       this.deuimpTipodocumento = deuimpTipodocumento;
       this.deuimpDocumento = deuimpDocumento;
       this.deuimpSexo = deuimpSexo;
       this.deuimpDireccion1 = deuimpDireccion1;
       this.deuimpDireccion2 = deuimpDireccion2;
       this.deuimpCelular = deuimpCelular;
       this.deuimpTelefono = deuimpTelefono;
       this.deuimpCorreoelectronico = deuimpCorreoelectronico;
       this.deuimpPlaca = deuimpPlaca;
       this.deuimpServiciovehiculo = deuimpServiciovehiculo;
       this.deuimpClasevehiculo = deuimpClasevehiculo;
       this.deuimpAvaluo = deuimpAvaluo;
       this.deuimpLiquidacionoficial = deuimpLiquidacionoficial;
       this.deuimpFechaliquidacion = deuimpFechaliquidacion;
       this.deuimpFechamatricula = deuimpFechamatricula;
       this.deuimpArchivoFk = deuimpArchivoFk;
    }
   
    public BigDecimal getDeuimpId() {
        return this.deuimpId;
    }
    
    public void setDeuimpId(BigDecimal deuimpId) {
        this.deuimpId = deuimpId;
    }
    public String getDeuimpConsecutivo() {
        return this.deuimpConsecutivo;
    }
    
    public void setDeuimpConsecutivo(String deuimpConsecutivo) {
        this.deuimpConsecutivo = deuimpConsecutivo;
    }
    public String getDeuimpFecha() {
        return this.deuimpFecha;
    }
    
    public void setDeuimpFecha(String deuimpFecha) {
        this.deuimpFecha = deuimpFecha;
    }
    public String getDeuimpTipo() {
        return this.deuimpTipo;
    }
    
    public void setDeuimpTipo(String deuimpTipo) {
        this.deuimpTipo = deuimpTipo;
    }
    public String getDeuimpValor() {
        return this.deuimpValor;
    }
    
    public void setDeuimpValor(String deuimpValor) {
        this.deuimpValor = deuimpValor;
    }
    public String getDeuimpMotivo() {
        return this.deuimpMotivo;
    }
    
    public void setDeuimpMotivo(String deuimpMotivo) {
        this.deuimpMotivo = deuimpMotivo;
    }
    public String getDeuimpReferencia() {
        return this.deuimpReferencia;
    }
    
    public void setDeuimpReferencia(String deuimpReferencia) {
        this.deuimpReferencia = deuimpReferencia;
    }
    public String getDeuimpNombre1() {
        return this.deuimpNombre1;
    }
    
    public void setDeuimpNombre1(String deuimpNombre1) {
        this.deuimpNombre1 = deuimpNombre1;
    }
    public String getDeuimpNombre2() {
        return this.deuimpNombre2;
    }
    
    public void setDeuimpNombre2(String deuimpNombre2) {
        this.deuimpNombre2 = deuimpNombre2;
    }
    public String getDeuimpApellido1() {
        return this.deuimpApellido1;
    }
    
    public void setDeuimpApellido1(String deuimpApellido1) {
        this.deuimpApellido1 = deuimpApellido1;
    }
    public String getDeuimpApellido2() {
        return this.deuimpApellido2;
    }
    
    public void setDeuimpApellido2(String deuimpApellido2) {
        this.deuimpApellido2 = deuimpApellido2;
    }
    public String getDeuimpTipodocumento() {
        return this.deuimpTipodocumento;
    }
    
    public void setDeuimpTipodocumento(String deuimpTipodocumento) {
        this.deuimpTipodocumento = deuimpTipodocumento;
    }
    public String getDeuimpDocumento() {
        return this.deuimpDocumento;
    }
    
    public void setDeuimpDocumento(String deuimpDocumento) {
        this.deuimpDocumento = deuimpDocumento;
    }
    public String getDeuimpSexo() {
        return this.deuimpSexo;
    }
    
    public void setDeuimpSexo(String deuimpSexo) {
        this.deuimpSexo = deuimpSexo;
    }
    public String getDeuimpDireccion1() {
        return this.deuimpDireccion1;
    }
    
    public void setDeuimpDireccion1(String deuimpDireccion1) {
        this.deuimpDireccion1 = deuimpDireccion1;
    }
    public String getDeuimpDireccion2() {
        return this.deuimpDireccion2;
    }
    
    public void setDeuimpDireccion2(String deuimpDireccion2) {
        this.deuimpDireccion2 = deuimpDireccion2;
    }
    public String getDeuimpCelular() {
        return this.deuimpCelular;
    }
    
    public void setDeuimpCelular(String deuimpCelular) {
        this.deuimpCelular = deuimpCelular;
    }
    public String getDeuimpTelefono() {
        return this.deuimpTelefono;
    }
    
    public void setDeuimpTelefono(String deuimpTelefono) {
        this.deuimpTelefono = deuimpTelefono;
    }
    public String getDeuimpCorreoelectronico() {
        return this.deuimpCorreoelectronico;
    }
    
    public void setDeuimpCorreoelectronico(String deuimpCorreoelectronico) {
        this.deuimpCorreoelectronico = deuimpCorreoelectronico;
    }
    public String getDeuimpPlaca() {
        return this.deuimpPlaca;
    }
    
    public void setDeuimpPlaca(String deuimpPlaca) {
        this.deuimpPlaca = deuimpPlaca;
    }
    public String getDeuimpServiciovehiculo() {
        return this.deuimpServiciovehiculo;
    }
    
    public void setDeuimpServiciovehiculo(String deuimpServiciovehiculo) {
        this.deuimpServiciovehiculo = deuimpServiciovehiculo;
    }
    public String getDeuimpClasevehiculo() {
        return this.deuimpClasevehiculo;
    }
    
    public void setDeuimpClasevehiculo(String deuimpClasevehiculo) {
        this.deuimpClasevehiculo = deuimpClasevehiculo;
    }
    public String getDeuimpAvaluo() {
        return this.deuimpAvaluo;
    }
    
    public void setDeuimpAvaluo(String deuimpAvaluo) {
        this.deuimpAvaluo = deuimpAvaluo;
    }
    public String getDeuimpLiquidacionoficial() {
        return this.deuimpLiquidacionoficial;
    }
    
    public void setDeuimpLiquidacionoficial(String deuimpLiquidacionoficial) {
        this.deuimpLiquidacionoficial = deuimpLiquidacionoficial;
    }
    public String getDeuimpFechaliquidacion() {
        return this.deuimpFechaliquidacion;
    }
    
    public void setDeuimpFechaliquidacion(String deuimpFechaliquidacion) {
        this.deuimpFechaliquidacion = deuimpFechaliquidacion;
    }
    public String getDeuimpFechamatricula() {
        return this.deuimpFechamatricula;
    }
    
    public void setDeuimpFechamatricula(String deuimpFechamatricula) {
        this.deuimpFechamatricula = deuimpFechamatricula;
    }
    public BigDecimal getDeuimpArchivoFk() {
        return this.deuimpArchivoFk;
    }
    
    public void setDeuimpArchivoFk(BigDecimal deuimpArchivoFk) {
        this.deuimpArchivoFk = deuimpArchivoFk;
    }




}


