package CobroCoactivo.Persistencia;
// Generated 28/06/2018 06:29:52 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * CivDetalleExpedientes generated by hbm2java
 */
public class CivDetalleExpedientes  implements java.io.Serializable {


     private BigDecimal detexpId;
     private CivExpedientes civExpedientes;
     private CivEstadoDetalleExpedientes civEstadoDetalleExpedientes;
     private CivTipoDetalleExpedientes civTipoDetalleExpedientes;
     private String detexpDescripcion;
     private Date detexpFechaproceso;

    public CivDetalleExpedientes() {
    }

	
    public CivDetalleExpedientes(BigDecimal detexpId, CivExpedientes civExpedientes, CivEstadoDetalleExpedientes civEstadoDetalleExpedientes, CivTipoDetalleExpedientes civTipoDetalleExpedientes, String detexpDescripcion) {
        this.detexpId = detexpId;
        this.civExpedientes = civExpedientes;
        this.civEstadoDetalleExpedientes = civEstadoDetalleExpedientes;
        this.civTipoDetalleExpedientes = civTipoDetalleExpedientes;
        this.detexpDescripcion = detexpDescripcion;
    }
    public CivDetalleExpedientes(BigDecimal detexpId, CivExpedientes civExpedientes, CivEstadoDetalleExpedientes civEstadoDetalleExpedientes, CivTipoDetalleExpedientes civTipoDetalleExpedientes, String detexpDescripcion, Date detexpFechaproceso) {
       this.detexpId = detexpId;
       this.civExpedientes = civExpedientes;
       this.civEstadoDetalleExpedientes = civEstadoDetalleExpedientes;
       this.civTipoDetalleExpedientes = civTipoDetalleExpedientes;
       this.detexpDescripcion = detexpDescripcion;
       this.detexpFechaproceso = detexpFechaproceso;
    }
   
    public BigDecimal getDetexpId() {
        return this.detexpId;
    }
    
    public void setDetexpId(BigDecimal detexpId) {
        this.detexpId = detexpId;
    }
    public CivExpedientes getCivExpedientes() {
        return this.civExpedientes;
    }
    
    public void setCivExpedientes(CivExpedientes civExpedientes) {
        this.civExpedientes = civExpedientes;
    }
    public CivEstadoDetalleExpedientes getCivEstadoDetalleExpedientes() {
        return this.civEstadoDetalleExpedientes;
    }
    
    public void setCivEstadoDetalleExpedientes(CivEstadoDetalleExpedientes civEstadoDetalleExpedientes) {
        this.civEstadoDetalleExpedientes = civEstadoDetalleExpedientes;
    }
    public CivTipoDetalleExpedientes getCivTipoDetalleExpedientes() {
        return this.civTipoDetalleExpedientes;
    }
    
    public void setCivTipoDetalleExpedientes(CivTipoDetalleExpedientes civTipoDetalleExpedientes) {
        this.civTipoDetalleExpedientes = civTipoDetalleExpedientes;
    }
    public String getDetexpDescripcion() {
        return this.detexpDescripcion;
    }
    
    public void setDetexpDescripcion(String detexpDescripcion) {
        this.detexpDescripcion = detexpDescripcion;
    }
    public Date getDetexpFechaproceso() {
        return this.detexpFechaproceso;
    }
    
    public void setDetexpFechaproceso(Date detexpFechaproceso) {
        this.detexpFechaproceso = detexpFechaproceso;
    }




}


