package CobroCoactivo.Persistencia;
// Generated 30/07/2018 08:55:07 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * CivEstadoPagos generated by hbm2java
 */
public class CivEstadoPagos  implements java.io.Serializable {


     private BigDecimal estpagId;
     private String estpagDescripcion;
     private Date estpagFechainicial;
     private Date estpagFechafinal;
     private Date column1;
     private Set civPagoses = new HashSet(0);

    public CivEstadoPagos() {
    }

	
    public CivEstadoPagos(BigDecimal estpagId) {
        this.estpagId = estpagId;
    }
    public CivEstadoPagos(BigDecimal estpagId, String estpagDescripcion, Date estpagFechainicial, Date estpagFechafinal, Date column1, Set civPagoses) {
       this.estpagId = estpagId;
       this.estpagDescripcion = estpagDescripcion;
       this.estpagFechainicial = estpagFechainicial;
       this.estpagFechafinal = estpagFechafinal;
       this.column1 = column1;
       this.civPagoses = civPagoses;
    }
   
    public BigDecimal getEstpagId() {
        return this.estpagId;
    }
    
    public void setEstpagId(BigDecimal estpagId) {
        this.estpagId = estpagId;
    }
    public String getEstpagDescripcion() {
        return this.estpagDescripcion;
    }
    
    public void setEstpagDescripcion(String estpagDescripcion) {
        this.estpagDescripcion = estpagDescripcion;
    }
    public Date getEstpagFechainicial() {
        return this.estpagFechainicial;
    }
    
    public void setEstpagFechainicial(Date estpagFechainicial) {
        this.estpagFechainicial = estpagFechainicial;
    }
    public Date getEstpagFechafinal() {
        return this.estpagFechafinal;
    }
    
    public void setEstpagFechafinal(Date estpagFechafinal) {
        this.estpagFechafinal = estpagFechafinal;
    }
    public Date getColumn1() {
        return this.column1;
    }
    
    public void setColumn1(Date column1) {
        this.column1 = column1;
    }
    public Set getCivPagoses() {
        return this.civPagoses;
    }
    
    public void setCivPagoses(Set civPagoses) {
        this.civPagoses = civPagoses;
    }




}


