package CobroCoactivo.Persistencia;
// Generated 26/07/2018 02:21:37 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * CivEstadoArchDetExp generated by hbm2java
 */
public class CivEstadoArchDetExp  implements java.io.Serializable {


     private BigDecimal estarcdetexpId;
     private String estarcdetexpDescripcion;
     private Date estarcdetexpFechainicial;
     private Date estarcdetexpFechafinal;
     private Date estarcdetexpFechaproceso;
     private CivArchivoDetExpedientes civArchivoDetExpedientes;

    public CivEstadoArchDetExp() {
    }

	
    public CivEstadoArchDetExp(BigDecimal estarcdetexpId, String estarcdetexpDescripcion, Date estarcdetexpFechainicial) {
        this.estarcdetexpId = estarcdetexpId;
        this.estarcdetexpDescripcion = estarcdetexpDescripcion;
        this.estarcdetexpFechainicial = estarcdetexpFechainicial;
    }
    public CivEstadoArchDetExp(BigDecimal estarcdetexpId, String estarcdetexpDescripcion, Date estarcdetexpFechainicial, Date estarcdetexpFechafinal, Date estarcdetexpFechaproceso, CivArchivoDetExpedientes civArchivoDetExpedientes) {
       this.estarcdetexpId = estarcdetexpId;
       this.estarcdetexpDescripcion = estarcdetexpDescripcion;
       this.estarcdetexpFechainicial = estarcdetexpFechainicial;
       this.estarcdetexpFechafinal = estarcdetexpFechafinal;
       this.estarcdetexpFechaproceso = estarcdetexpFechaproceso;
       this.civArchivoDetExpedientes = civArchivoDetExpedientes;
    }
   
    public BigDecimal getEstarcdetexpId() {
        return this.estarcdetexpId;
    }
    
    public void setEstarcdetexpId(BigDecimal estarcdetexpId) {
        this.estarcdetexpId = estarcdetexpId;
    }
    public String getEstarcdetexpDescripcion() {
        return this.estarcdetexpDescripcion;
    }
    
    public void setEstarcdetexpDescripcion(String estarcdetexpDescripcion) {
        this.estarcdetexpDescripcion = estarcdetexpDescripcion;
    }
    public Date getEstarcdetexpFechainicial() {
        return this.estarcdetexpFechainicial;
    }
    
    public void setEstarcdetexpFechainicial(Date estarcdetexpFechainicial) {
        this.estarcdetexpFechainicial = estarcdetexpFechainicial;
    }
    public Date getEstarcdetexpFechafinal() {
        return this.estarcdetexpFechafinal;
    }
    
    public void setEstarcdetexpFechafinal(Date estarcdetexpFechafinal) {
        this.estarcdetexpFechafinal = estarcdetexpFechafinal;
    }
    public Date getEstarcdetexpFechaproceso() {
        return this.estarcdetexpFechaproceso;
    }
    
    public void setEstarcdetexpFechaproceso(Date estarcdetexpFechaproceso) {
        this.estarcdetexpFechaproceso = estarcdetexpFechaproceso;
    }
    public CivArchivoDetExpedientes getCivArchivoDetExpedientes() {
        return this.civArchivoDetExpedientes;
    }
    
    public void setCivArchivoDetExpedientes(CivArchivoDetExpedientes civArchivoDetExpedientes) {
        this.civArchivoDetExpedientes = civArchivoDetExpedientes;
    }




}


