package CobroCoactivo.Persistencia;
// Generated 10/08/2018 01:53:59 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * CivEstadoDetalleExpedientes generated by hbm2java
 */
public class CivEstadoDetalleExpedientes  implements java.io.Serializable {


     private BigDecimal estdetexpId;
     private String estdetexpDescripcion;
     private Date estdetexpFechainicial;
     private Date estdetexpFechafinal;
     private Date estdetexpFechaproceso;
     private Set civDetalleExpedienteses = new HashSet(0);

    public CivEstadoDetalleExpedientes() {
    }

	
    public CivEstadoDetalleExpedientes(BigDecimal estdetexpId, String estdetexpDescripcion, Date estdetexpFechainicial) {
        this.estdetexpId = estdetexpId;
        this.estdetexpDescripcion = estdetexpDescripcion;
        this.estdetexpFechainicial = estdetexpFechainicial;
    }
    public CivEstadoDetalleExpedientes(BigDecimal estdetexpId, String estdetexpDescripcion, Date estdetexpFechainicial, Date estdetexpFechafinal, Date estdetexpFechaproceso, Set civDetalleExpedienteses) {
       this.estdetexpId = estdetexpId;
       this.estdetexpDescripcion = estdetexpDescripcion;
       this.estdetexpFechainicial = estdetexpFechainicial;
       this.estdetexpFechafinal = estdetexpFechafinal;
       this.estdetexpFechaproceso = estdetexpFechaproceso;
       this.civDetalleExpedienteses = civDetalleExpedienteses;
    }
   
    public BigDecimal getEstdetexpId() {
        return this.estdetexpId;
    }
    
    public void setEstdetexpId(BigDecimal estdetexpId) {
        this.estdetexpId = estdetexpId;
    }
    public String getEstdetexpDescripcion() {
        return this.estdetexpDescripcion;
    }
    
    public void setEstdetexpDescripcion(String estdetexpDescripcion) {
        this.estdetexpDescripcion = estdetexpDescripcion;
    }
    public Date getEstdetexpFechainicial() {
        return this.estdetexpFechainicial;
    }
    
    public void setEstdetexpFechainicial(Date estdetexpFechainicial) {
        this.estdetexpFechainicial = estdetexpFechainicial;
    }
    public Date getEstdetexpFechafinal() {
        return this.estdetexpFechafinal;
    }
    
    public void setEstdetexpFechafinal(Date estdetexpFechafinal) {
        this.estdetexpFechafinal = estdetexpFechafinal;
    }
    public Date getEstdetexpFechaproceso() {
        return this.estdetexpFechaproceso;
    }
    
    public void setEstdetexpFechaproceso(Date estdetexpFechaproceso) {
        this.estdetexpFechaproceso = estdetexpFechaproceso;
    }
    public Set getCivDetalleExpedienteses() {
        return this.civDetalleExpedienteses;
    }
    
    public void setCivDetalleExpedienteses(Set civDetalleExpedienteses) {
        this.civDetalleExpedienteses = civDetalleExpedienteses;
    }




}


