package CobroCoactivo.Persistencia;
// Generated 30/05/2018 02:43:14 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * CivEstadoFasesTrabajos generated by hbm2java
 */
public class CivEstadoFasesTrabajos  implements java.io.Serializable {


     private BigDecimal estfastraId;
     private String estfastraDescripcion;
     private Date estfastraFechainicial;
     private Date estfastraFechafinal;
     private Date estfastraFechaproceso;
     private CivFasesTrabajos civFasesTrabajos;

    public CivEstadoFasesTrabajos() {
    }

	
    public CivEstadoFasesTrabajos(BigDecimal estfastraId, String estfastraDescripcion) {
        this.estfastraId = estfastraId;
        this.estfastraDescripcion = estfastraDescripcion;
    }
    public CivEstadoFasesTrabajos(BigDecimal estfastraId, String estfastraDescripcion, Date estfastraFechainicial, Date estfastraFechafinal, Date estfastraFechaproceso, CivFasesTrabajos civFasesTrabajos) {
       this.estfastraId = estfastraId;
       this.estfastraDescripcion = estfastraDescripcion;
       this.estfastraFechainicial = estfastraFechainicial;
       this.estfastraFechafinal = estfastraFechafinal;
       this.estfastraFechaproceso = estfastraFechaproceso;
       this.civFasesTrabajos = civFasesTrabajos;
    }
   
    public BigDecimal getEstfastraId() {
        return this.estfastraId;
    }
    
    public void setEstfastraId(BigDecimal estfastraId) {
        this.estfastraId = estfastraId;
    }
    public String getEstfastraDescripcion() {
        return this.estfastraDescripcion;
    }
    
    public void setEstfastraDescripcion(String estfastraDescripcion) {
        this.estfastraDescripcion = estfastraDescripcion;
    }
    public Date getEstfastraFechainicial() {
        return this.estfastraFechainicial;
    }
    
    public void setEstfastraFechainicial(Date estfastraFechainicial) {
        this.estfastraFechainicial = estfastraFechainicial;
    }
    public Date getEstfastraFechafinal() {
        return this.estfastraFechafinal;
    }
    
    public void setEstfastraFechafinal(Date estfastraFechafinal) {
        this.estfastraFechafinal = estfastraFechafinal;
    }
    public Date getEstfastraFechaproceso() {
        return this.estfastraFechaproceso;
    }
    
    public void setEstfastraFechaproceso(Date estfastraFechaproceso) {
        this.estfastraFechaproceso = estfastraFechaproceso;
    }
    public CivFasesTrabajos getCivFasesTrabajos() {
        return this.civFasesTrabajos;
    }
    
    public void setCivFasesTrabajos(CivFasesTrabajos civFasesTrabajos) {
        this.civFasesTrabajos = civFasesTrabajos;
    }




}


