package CobroCoactivo.Persistencia;
// Generated 30/08/2018 09:56:13 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * CivExcepciones generated by hbm2java
 */
public class CivExcepciones  implements java.io.Serializable {


     private BigDecimal excId;
     private CivUsuarios civUsuarios;
     private CivTipoExcepcion civTipoExcepcion;
     private CivMovimientos civMovimientos;
     private CivEstadoExcepcion civEstadoExcepcion;
     private CivArchivoDetExpedientes civArchivoDetExpedientes;
     private Date excFechaproceso;
     private Date excFechaRadicado;
     private String excNumeroRadicado;

    public CivExcepciones() {
    }

	
    public CivExcepciones(BigDecimal excId, CivUsuarios civUsuarios, CivTipoExcepcion civTipoExcepcion, CivEstadoExcepcion civEstadoExcepcion, CivArchivoDetExpedientes civArchivoDetExpedientes, Date excFechaRadicado, String excNumeroRadicado) {
        this.excId = excId;
        this.civUsuarios = civUsuarios;
        this.civTipoExcepcion = civTipoExcepcion;
        this.civEstadoExcepcion = civEstadoExcepcion;
        this.civArchivoDetExpedientes = civArchivoDetExpedientes;
        this.excFechaRadicado = excFechaRadicado;
        this.excNumeroRadicado = excNumeroRadicado;
    }
    public CivExcepciones(BigDecimal excId, CivUsuarios civUsuarios, CivTipoExcepcion civTipoExcepcion, CivMovimientos civMovimientos, CivEstadoExcepcion civEstadoExcepcion, CivArchivoDetExpedientes civArchivoDetExpedientes, Date excFechaproceso, Date excFechaRadicado, String excNumeroRadicado) {
       this.excId = excId;
       this.civUsuarios = civUsuarios;
       this.civTipoExcepcion = civTipoExcepcion;
       this.civMovimientos = civMovimientos;
       this.civEstadoExcepcion = civEstadoExcepcion;
       this.civArchivoDetExpedientes = civArchivoDetExpedientes;
       this.excFechaproceso = excFechaproceso;
       this.excFechaRadicado = excFechaRadicado;
       this.excNumeroRadicado = excNumeroRadicado;
    }
   
    public BigDecimal getExcId() {
        return this.excId;
    }
    
    public void setExcId(BigDecimal excId) {
        this.excId = excId;
    }
    public CivUsuarios getCivUsuarios() {
        return this.civUsuarios;
    }
    
    public void setCivUsuarios(CivUsuarios civUsuarios) {
        this.civUsuarios = civUsuarios;
    }
    public CivTipoExcepcion getCivTipoExcepcion() {
        return this.civTipoExcepcion;
    }
    
    public void setCivTipoExcepcion(CivTipoExcepcion civTipoExcepcion) {
        this.civTipoExcepcion = civTipoExcepcion;
    }
    public CivMovimientos getCivMovimientos() {
        return this.civMovimientos;
    }
    
    public void setCivMovimientos(CivMovimientos civMovimientos) {
        this.civMovimientos = civMovimientos;
    }
    public CivEstadoExcepcion getCivEstadoExcepcion() {
        return this.civEstadoExcepcion;
    }
    
    public void setCivEstadoExcepcion(CivEstadoExcepcion civEstadoExcepcion) {
        this.civEstadoExcepcion = civEstadoExcepcion;
    }
    public CivArchivoDetExpedientes getCivArchivoDetExpedientes() {
        return this.civArchivoDetExpedientes;
    }
    
    public void setCivArchivoDetExpedientes(CivArchivoDetExpedientes civArchivoDetExpedientes) {
        this.civArchivoDetExpedientes = civArchivoDetExpedientes;
    }
    public Date getExcFechaproceso() {
        return this.excFechaproceso;
    }
    
    public void setExcFechaproceso(Date excFechaproceso) {
        this.excFechaproceso = excFechaproceso;
    }
    public Date getExcFechaRadicado() {
        return this.excFechaRadicado;
    }
    
    public void setExcFechaRadicado(Date excFechaRadicado) {
        this.excFechaRadicado = excFechaRadicado;
    }
    public String getExcNumeroRadicado() {
        return this.excNumeroRadicado;
    }
    
    public void setExcNumeroRadicado(String excNumeroRadicado) {
        this.excNumeroRadicado = excNumeroRadicado;
    }




}


