package CobroCoactivo.Persistencia;
// Generated 13/07/2018 10:45:24 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * CivEstadoMovimientos generated by hbm2java
 */
public class CivEstadoMovimientos  implements java.io.Serializable {


     private BigDecimal estmovId;
     private String estmovDescripcion;
     private Date estmovFechainicial;
     private Date estmovFechafinal;
     private Date estmovFechaproceso;
     private Set civMovimientoses = new HashSet(0);

    public CivEstadoMovimientos() {
    }

	
    public CivEstadoMovimientos(BigDecimal estmovId, String estmovDescripcion, Date estmovFechainicial) {
        this.estmovId = estmovId;
        this.estmovDescripcion = estmovDescripcion;
        this.estmovFechainicial = estmovFechainicial;
    }
    public CivEstadoMovimientos(BigDecimal estmovId, String estmovDescripcion, Date estmovFechainicial, Date estmovFechafinal, Date estmovFechaproceso, Set civMovimientoses) {
       this.estmovId = estmovId;
       this.estmovDescripcion = estmovDescripcion;
       this.estmovFechainicial = estmovFechainicial;
       this.estmovFechafinal = estmovFechafinal;
       this.estmovFechaproceso = estmovFechaproceso;
       this.civMovimientoses = civMovimientoses;
    }
   
    public BigDecimal getEstmovId() {
        return this.estmovId;
    }
    
    public void setEstmovId(BigDecimal estmovId) {
        this.estmovId = estmovId;
    }
    public String getEstmovDescripcion() {
        return this.estmovDescripcion;
    }
    
    public void setEstmovDescripcion(String estmovDescripcion) {
        this.estmovDescripcion = estmovDescripcion;
    }
    public Date getEstmovFechainicial() {
        return this.estmovFechainicial;
    }
    
    public void setEstmovFechainicial(Date estmovFechainicial) {
        this.estmovFechainicial = estmovFechainicial;
    }
    public Date getEstmovFechafinal() {
        return this.estmovFechafinal;
    }
    
    public void setEstmovFechafinal(Date estmovFechafinal) {
        this.estmovFechafinal = estmovFechafinal;
    }
    public Date getEstmovFechaproceso() {
        return this.estmovFechaproceso;
    }
    
    public void setEstmovFechaproceso(Date estmovFechaproceso) {
        this.estmovFechaproceso = estmovFechaproceso;
    }
    public Set getCivMovimientoses() {
        return this.civMovimientoses;
    }
    
    public void setCivMovimientoses(Set civMovimientoses) {
        this.civMovimientoses = civMovimientoses;
    }




}


