package CobroCoactivo.Persistencia;
// Generated 9/08/2018 03:19:23 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * CivEstadoSolicitudes generated by hbm2java
 */
public class CivEstadoSolicitudes  implements java.io.Serializable {


     private BigDecimal estsolId;
     private String estsolNombre;
     private Date estsolFechaproceso;
     private Date estsolFechainicial;
     private Date estsolFechafinal;
     private Set civSolicitudeses = new HashSet(0);

    public CivEstadoSolicitudes() {
    }

	
    public CivEstadoSolicitudes(BigDecimal estsolId, String estsolNombre) {
        this.estsolId = estsolId;
        this.estsolNombre = estsolNombre;
    }
    public CivEstadoSolicitudes(BigDecimal estsolId, String estsolNombre, Date estsolFechaproceso, Date estsolFechainicial, Date estsolFechafinal, Set civSolicitudeses) {
       this.estsolId = estsolId;
       this.estsolNombre = estsolNombre;
       this.estsolFechaproceso = estsolFechaproceso;
       this.estsolFechainicial = estsolFechainicial;
       this.estsolFechafinal = estsolFechafinal;
       this.civSolicitudeses = civSolicitudeses;
    }
   
    public BigDecimal getEstsolId() {
        return this.estsolId;
    }
    
    public void setEstsolId(BigDecimal estsolId) {
        this.estsolId = estsolId;
    }
    public String getEstsolNombre() {
        return this.estsolNombre;
    }
    
    public void setEstsolNombre(String estsolNombre) {
        this.estsolNombre = estsolNombre;
    }
    public Date getEstsolFechaproceso() {
        return this.estsolFechaproceso;
    }
    
    public void setEstsolFechaproceso(Date estsolFechaproceso) {
        this.estsolFechaproceso = estsolFechaproceso;
    }
    public Date getEstsolFechainicial() {
        return this.estsolFechainicial;
    }
    
    public void setEstsolFechainicial(Date estsolFechainicial) {
        this.estsolFechainicial = estsolFechainicial;
    }
    public Date getEstsolFechafinal() {
        return this.estsolFechafinal;
    }
    
    public void setEstsolFechafinal(Date estsolFechafinal) {
        this.estsolFechafinal = estsolFechafinal;
    }
    public Set getCivSolicitudeses() {
        return this.civSolicitudeses;
    }
    
    public void setCivSolicitudeses(Set civSolicitudeses) {
        this.civSolicitudeses = civSolicitudeses;
    }




}


