package CobroCoactivo.Persistencia;
// Generated 30/08/2018 09:56:13 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * CivEstadoDetallePago generated by hbm2java
 */
public class CivEstadoDetallePago  implements java.io.Serializable {


     private BigDecimal estdetpagId;
     private String estdetpagDescripcion;
     private Date estdetpagFechainicial;
     private Date estdetpagFechafinal;
     private Date estdetpagFechaproceso;
     private Set civDetallePagoses = new HashSet(0);

    public CivEstadoDetallePago() {
    }

	
    public CivEstadoDetallePago(BigDecimal estdetpagId) {
        this.estdetpagId = estdetpagId;
    }
    public CivEstadoDetallePago(BigDecimal estdetpagId, String estdetpagDescripcion, Date estdetpagFechainicial, Date estdetpagFechafinal, Date estdetpagFechaproceso, Set civDetallePagoses) {
       this.estdetpagId = estdetpagId;
       this.estdetpagDescripcion = estdetpagDescripcion;
       this.estdetpagFechainicial = estdetpagFechainicial;
       this.estdetpagFechafinal = estdetpagFechafinal;
       this.estdetpagFechaproceso = estdetpagFechaproceso;
       this.civDetallePagoses = civDetallePagoses;
    }
   
    public BigDecimal getEstdetpagId() {
        return this.estdetpagId;
    }
    
    public void setEstdetpagId(BigDecimal estdetpagId) {
        this.estdetpagId = estdetpagId;
    }
    public String getEstdetpagDescripcion() {
        return this.estdetpagDescripcion;
    }
    
    public void setEstdetpagDescripcion(String estdetpagDescripcion) {
        this.estdetpagDescripcion = estdetpagDescripcion;
    }
    public Date getEstdetpagFechainicial() {
        return this.estdetpagFechainicial;
    }
    
    public void setEstdetpagFechainicial(Date estdetpagFechainicial) {
        this.estdetpagFechainicial = estdetpagFechainicial;
    }
    public Date getEstdetpagFechafinal() {
        return this.estdetpagFechafinal;
    }
    
    public void setEstdetpagFechafinal(Date estdetpagFechafinal) {
        this.estdetpagFechafinal = estdetpagFechafinal;
    }
    public Date getEstdetpagFechaproceso() {
        return this.estdetpagFechaproceso;
    }
    
    public void setEstdetpagFechaproceso(Date estdetpagFechaproceso) {
        this.estdetpagFechaproceso = estdetpagFechaproceso;
    }
    public Set getCivDetallePagoses() {
        return this.civDetallePagoses;
    }
    
    public void setCivDetallePagoses(Set civDetallePagoses) {
        this.civDetallePagoses = civDetallePagoses;
    }




}


