package CobroCoactivo.Persistencia;
// Generated 27/07/2018 01:43:20 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * CivEstadoTipoDetalleCobro generated by hbm2java
 */
public class CivEstadoTipoDetalleCobro  implements java.io.Serializable {


     private BigDecimal esttipdetcobId;
     private String esttipdetcobDescripcion;
     private Date esttipdetcobFechainicial;
     private Date esttipdetcobFechafinal;
     private Date esttipdetcobFechaproceso;
     private Set civTipoDetalleCobros = new HashSet(0);

    public CivEstadoTipoDetalleCobro() {
    }

	
    public CivEstadoTipoDetalleCobro(BigDecimal esttipdetcobId, String esttipdetcobDescripcion) {
        this.esttipdetcobId = esttipdetcobId;
        this.esttipdetcobDescripcion = esttipdetcobDescripcion;
    }
    public CivEstadoTipoDetalleCobro(BigDecimal esttipdetcobId, String esttipdetcobDescripcion, Date esttipdetcobFechainicial, Date esttipdetcobFechafinal, Date esttipdetcobFechaproceso, Set civTipoDetalleCobros) {
       this.esttipdetcobId = esttipdetcobId;
       this.esttipdetcobDescripcion = esttipdetcobDescripcion;
       this.esttipdetcobFechainicial = esttipdetcobFechainicial;
       this.esttipdetcobFechafinal = esttipdetcobFechafinal;
       this.esttipdetcobFechaproceso = esttipdetcobFechaproceso;
       this.civTipoDetalleCobros = civTipoDetalleCobros;
    }
   
    public BigDecimal getEsttipdetcobId() {
        return this.esttipdetcobId;
    }
    
    public void setEsttipdetcobId(BigDecimal esttipdetcobId) {
        this.esttipdetcobId = esttipdetcobId;
    }
    public String getEsttipdetcobDescripcion() {
        return this.esttipdetcobDescripcion;
    }
    
    public void setEsttipdetcobDescripcion(String esttipdetcobDescripcion) {
        this.esttipdetcobDescripcion = esttipdetcobDescripcion;
    }
    public Date getEsttipdetcobFechainicial() {
        return this.esttipdetcobFechainicial;
    }
    
    public void setEsttipdetcobFechainicial(Date esttipdetcobFechainicial) {
        this.esttipdetcobFechainicial = esttipdetcobFechainicial;
    }
    public Date getEsttipdetcobFechafinal() {
        return this.esttipdetcobFechafinal;
    }
    
    public void setEsttipdetcobFechafinal(Date esttipdetcobFechafinal) {
        this.esttipdetcobFechafinal = esttipdetcobFechafinal;
    }
    public Date getEsttipdetcobFechaproceso() {
        return this.esttipdetcobFechaproceso;
    }
    
    public void setEsttipdetcobFechaproceso(Date esttipdetcobFechaproceso) {
        this.esttipdetcobFechaproceso = esttipdetcobFechaproceso;
    }
    public Set getCivTipoDetalleCobros() {
        return this.civTipoDetalleCobros;
    }
    
    public void setCivTipoDetalleCobros(Set civTipoDetalleCobros) {
        this.civTipoDetalleCobros = civTipoDetalleCobros;
    }




}


