package CobroCoactivo.Persistencia;
// Generated 30/08/2018 09:56:13 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * CivFinanciacion generated by hbm2java
 */
public class CivFinanciacion  implements java.io.Serializable {


     private BigDecimal finId;
     private CivUsuarios civUsuarios;
     private CivEstadoFinanciacion civEstadoFinanciacion;
     private String finNumero;
     private BigDecimal finValor;
     private Date finFecha;

    public CivFinanciacion() {
    }

	
    public CivFinanciacion(BigDecimal finId) {
        this.finId = finId;
    }
    public CivFinanciacion(BigDecimal finId, CivUsuarios civUsuarios, CivEstadoFinanciacion civEstadoFinanciacion, String finNumero, BigDecimal finValor, Date finFecha) {
       this.finId = finId;
       this.civUsuarios = civUsuarios;
       this.civEstadoFinanciacion = civEstadoFinanciacion;
       this.finNumero = finNumero;
       this.finValor = finValor;
       this.finFecha = finFecha;
    }
   
    public BigDecimal getFinId() {
        return this.finId;
    }
    
    public void setFinId(BigDecimal finId) {
        this.finId = finId;
    }
    public CivUsuarios getCivUsuarios() {
        return this.civUsuarios;
    }
    
    public void setCivUsuarios(CivUsuarios civUsuarios) {
        this.civUsuarios = civUsuarios;
    }
    public CivEstadoFinanciacion getCivEstadoFinanciacion() {
        return this.civEstadoFinanciacion;
    }
    
    public void setCivEstadoFinanciacion(CivEstadoFinanciacion civEstadoFinanciacion) {
        this.civEstadoFinanciacion = civEstadoFinanciacion;
    }
    public String getFinNumero() {
        return this.finNumero;
    }
    
    public void setFinNumero(String finNumero) {
        this.finNumero = finNumero;
    }
    public BigDecimal getFinValor() {
        return this.finValor;
    }
    
    public void setFinValor(BigDecimal finValor) {
        this.finValor = finValor;
    }
    public Date getFinFecha() {
        return this.finFecha;
    }
    
    public void setFinFecha(Date finFecha) {
        this.finFecha = finFecha;
    }




}


