package CobroCoactivo.Persistencia;
// Generated 30/05/2018 02:43:14 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * CivFasesTrabajos generated by hbm2java
 */
public class CivFasesTrabajos  implements java.io.Serializable {


     private BigDecimal fastraId;
     private CivReporteTrabajos civReporteTrabajos;
     private CivEtapasTrabajos civEtapasTrabajos;
     private CivEstadoFasesTrabajos civEstadoFasesTrabajos;
     private String fastraDescripcion;
     private BigDecimal fastraEstfastraFk;
     private Date fastraFechaproceso;
     private BigDecimal fastraDianim;
     private BigDecimal fastraDiamax;

    public CivFasesTrabajos() {
    }

	
    public CivFasesTrabajos(CivEtapasTrabajos civEtapasTrabajos, CivEstadoFasesTrabajos civEstadoFasesTrabajos, String fastraDescripcion, BigDecimal fastraEstfastraFk) {
        this.civEtapasTrabajos = civEtapasTrabajos;
        this.civEstadoFasesTrabajos = civEstadoFasesTrabajos;
        this.fastraDescripcion = fastraDescripcion;
        this.fastraEstfastraFk = fastraEstfastraFk;
    }
    public CivFasesTrabajos(CivReporteTrabajos civReporteTrabajos, CivEtapasTrabajos civEtapasTrabajos, CivEstadoFasesTrabajos civEstadoFasesTrabajos, String fastraDescripcion, BigDecimal fastraEstfastraFk, Date fastraFechaproceso, BigDecimal fastraDianim, BigDecimal fastraDiamax) {
       this.civReporteTrabajos = civReporteTrabajos;
       this.civEtapasTrabajos = civEtapasTrabajos;
       this.civEstadoFasesTrabajos = civEstadoFasesTrabajos;
       this.fastraDescripcion = fastraDescripcion;
       this.fastraEstfastraFk = fastraEstfastraFk;
       this.fastraFechaproceso = fastraFechaproceso;
       this.fastraDianim = fastraDianim;
       this.fastraDiamax = fastraDiamax;
    }
   
    public BigDecimal getFastraId() {
        return this.fastraId;
    }
    
    public void setFastraId(BigDecimal fastraId) {
        this.fastraId = fastraId;
    }
    public CivReporteTrabajos getCivReporteTrabajos() {
        return this.civReporteTrabajos;
    }
    
    public void setCivReporteTrabajos(CivReporteTrabajos civReporteTrabajos) {
        this.civReporteTrabajos = civReporteTrabajos;
    }
    public CivEtapasTrabajos getCivEtapasTrabajos() {
        return this.civEtapasTrabajos;
    }
    
    public void setCivEtapasTrabajos(CivEtapasTrabajos civEtapasTrabajos) {
        this.civEtapasTrabajos = civEtapasTrabajos;
    }
    public CivEstadoFasesTrabajos getCivEstadoFasesTrabajos() {
        return this.civEstadoFasesTrabajos;
    }
    
    public void setCivEstadoFasesTrabajos(CivEstadoFasesTrabajos civEstadoFasesTrabajos) {
        this.civEstadoFasesTrabajos = civEstadoFasesTrabajos;
    }
    public String getFastraDescripcion() {
        return this.fastraDescripcion;
    }
    
    public void setFastraDescripcion(String fastraDescripcion) {
        this.fastraDescripcion = fastraDescripcion;
    }
    public BigDecimal getFastraEstfastraFk() {
        return this.fastraEstfastraFk;
    }
    
    public void setFastraEstfastraFk(BigDecimal fastraEstfastraFk) {
        this.fastraEstfastraFk = fastraEstfastraFk;
    }
    public Date getFastraFechaproceso() {
        return this.fastraFechaproceso;
    }
    
    public void setFastraFechaproceso(Date fastraFechaproceso) {
        this.fastraFechaproceso = fastraFechaproceso;
    }
    public BigDecimal getFastraDianim() {
        return this.fastraDianim;
    }
    
    public void setFastraDianim(BigDecimal fastraDianim) {
        this.fastraDianim = fastraDianim;
    }
    public BigDecimal getFastraDiamax() {
        return this.fastraDiamax;
    }
    
    public void setFastraDiamax(BigDecimal fastraDiamax) {
        this.fastraDiamax = fastraDiamax;
    }




}


