package CobroCoactivo.Persistencia;
// Generated 28/06/2018 06:29:52 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * CivMovimientos generated by hbm2java
 */
public class CivMovimientos  implements java.io.Serializable {


     private BigDecimal movId;
     private CivDeudas civDeudas;
     private CivPersonas civPersonas;
     private CivEstadoMovimientos civEstadoMovimientos;
     private CivUsuarios civUsuarios;
     private CivFasesTrabajos civFasesTrabajos;
     private Date movFechaproceso;

    public CivMovimientos() {
    }

	
    public CivMovimientos(BigDecimal movId, CivDeudas civDeudas, CivPersonas civPersonas, CivEstadoMovimientos civEstadoMovimientos, CivUsuarios civUsuarios, CivFasesTrabajos civFasesTrabajos) {
        this.movId = movId;
        this.civDeudas = civDeudas;
        this.civPersonas = civPersonas;
        this.civEstadoMovimientos = civEstadoMovimientos;
        this.civUsuarios = civUsuarios;
        this.civFasesTrabajos = civFasesTrabajos;
    }
    public CivMovimientos(BigDecimal movId, CivDeudas civDeudas, CivPersonas civPersonas, CivEstadoMovimientos civEstadoMovimientos, CivUsuarios civUsuarios, CivFasesTrabajos civFasesTrabajos, Date movFechaproceso) {
       this.movId = movId;
       this.civDeudas = civDeudas;
       this.civPersonas = civPersonas;
       this.civEstadoMovimientos = civEstadoMovimientos;
       this.civUsuarios = civUsuarios;
       this.civFasesTrabajos = civFasesTrabajos;
       this.movFechaproceso = movFechaproceso;
    }
   
    public BigDecimal getMovId() {
        return this.movId;
    }
    
    public void setMovId(BigDecimal movId) {
        this.movId = movId;
    }
    public CivDeudas getCivDeudas() {
        return this.civDeudas;
    }
    
    public void setCivDeudas(CivDeudas civDeudas) {
        this.civDeudas = civDeudas;
    }
    public CivPersonas getCivPersonas() {
        return this.civPersonas;
    }
    
    public void setCivPersonas(CivPersonas civPersonas) {
        this.civPersonas = civPersonas;
    }
    public CivEstadoMovimientos getCivEstadoMovimientos() {
        return this.civEstadoMovimientos;
    }
    
    public void setCivEstadoMovimientos(CivEstadoMovimientos civEstadoMovimientos) {
        this.civEstadoMovimientos = civEstadoMovimientos;
    }
    public CivUsuarios getCivUsuarios() {
        return this.civUsuarios;
    }
    
    public void setCivUsuarios(CivUsuarios civUsuarios) {
        this.civUsuarios = civUsuarios;
    }
    public CivFasesTrabajos getCivFasesTrabajos() {
        return this.civFasesTrabajos;
    }
    
    public void setCivFasesTrabajos(CivFasesTrabajos civFasesTrabajos) {
        this.civFasesTrabajos = civFasesTrabajos;
    }
    public Date getMovFechaproceso() {
        return this.movFechaproceso;
    }
    
    public void setMovFechaproceso(Date movFechaproceso) {
        this.movFechaproceso = movFechaproceso;
    }




}


