package CobroCoactivo.Persistencia;
// Generated 28/06/2018 06:29:52 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * CivPlanTrabajos generated by hbm2java
 */
public class CivPlanTrabajos  implements java.io.Serializable {


     private BigDecimal platraId;
     private CivEstadoPlanTrabajos civEstadoPlanTrabajos;
     private String platraDescripcion;
     private Date platraFechaproceso;
     private String platraColor;
     private Set civDeudases = new HashSet(0);
     private Set civEtapasTrabajoses = new HashSet(0);

    public CivPlanTrabajos() {
    }

	
    public CivPlanTrabajos(BigDecimal platraId, CivEstadoPlanTrabajos civEstadoPlanTrabajos, String platraDescripcion) {
        this.platraId = platraId;
        this.civEstadoPlanTrabajos = civEstadoPlanTrabajos;
        this.platraDescripcion = platraDescripcion;
    }
    public CivPlanTrabajos(BigDecimal platraId, CivEstadoPlanTrabajos civEstadoPlanTrabajos, String platraDescripcion, Date platraFechaproceso, Set civDeudases, Set civEtapasTrabajoses) {
       this.platraId = platraId;
       this.civEstadoPlanTrabajos = civEstadoPlanTrabajos;
       this.platraDescripcion = platraDescripcion;
       this.platraFechaproceso = platraFechaproceso;
       this.civDeudases = civDeudases;
       this.civEtapasTrabajoses = civEtapasTrabajoses;
    }
   
    public BigDecimal getPlatraId() {
        return this.platraId;
    }
    
    public void setPlatraId(BigDecimal platraId) {
        this.platraId = platraId;
    }
    public CivEstadoPlanTrabajos getCivEstadoPlanTrabajos() {
        return this.civEstadoPlanTrabajos;
    }
    
    public void setCivEstadoPlanTrabajos(CivEstadoPlanTrabajos civEstadoPlanTrabajos) {
        this.civEstadoPlanTrabajos = civEstadoPlanTrabajos;
    }
    public String getPlatraDescripcion() {
        return this.platraDescripcion;
    }
    
    public void setPlatraDescripcion(String platraDescripcion) {
        this.platraDescripcion = platraDescripcion;
    }
    public Date getPlatraFechaproceso() {
        return this.platraFechaproceso;
    }
    
    public void setPlatraFechaproceso(Date platraFechaproceso) {
        this.platraFechaproceso = platraFechaproceso;
    }
    public Set getCivDeudases() {
        return this.civDeudases;
    }
    
    public void setCivDeudases(Set civDeudases) {
        this.civDeudases = civDeudases;
    }
    public Set getCivEtapasTrabajoses() {
        return this.civEtapasTrabajoses;
    }
    
    public void setCivEtapasTrabajoses(Set civEtapasTrabajoses) {
        this.civEtapasTrabajoses = civEtapasTrabajoses;
    }

    /**
     * @return the platraColor
     */
    public String getPlatraColor() {
        return platraColor;
    }

    /**
     * @param platraColor the platraColor to set
     */
    public void setPlatraColor(String platraColor) {
        this.platraColor = platraColor;
    }




}


