package CobroCoactivo.Persistencia;
// Generated 27/07/2018 01:43:20 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * CivTipoDocumentos generated by hbm2java
 */
public class CivTipoDocumentos  implements java.io.Serializable {


     private BigDecimal tipdocId;
     private String tipdocDescripcion;
     private String tipdocNombrecorto;
     private Date tipdocFechainicial;
     private Date tipdocFechafinal;
     private BigDecimal tipdocCodigo;
     private Set civPersonases = new HashSet(0);

    public CivTipoDocumentos() {
    }

	
    public CivTipoDocumentos(BigDecimal tipdocId, String tipdocDescripcion, Date tipdocFechainicial) {
        this.tipdocId = tipdocId;
        this.tipdocDescripcion = tipdocDescripcion;
        this.tipdocFechainicial = tipdocFechainicial;
    }
    public CivTipoDocumentos(BigDecimal tipdocId, String tipdocDescripcion, String tipdocNombrecorto, Date tipdocFechainicial, Date tipdocFechafinal, BigDecimal tipdocCodigo, Set civPersonases) {
       this.tipdocId = tipdocId;
       this.tipdocDescripcion = tipdocDescripcion;
       this.tipdocNombrecorto = tipdocNombrecorto;
       this.tipdocFechainicial = tipdocFechainicial;
       this.tipdocFechafinal = tipdocFechafinal;
       this.tipdocCodigo = tipdocCodigo;
       this.civPersonases = civPersonases;
    }
   
    public BigDecimal getTipdocId() {
        return this.tipdocId;
    }
    
    public void setTipdocId(BigDecimal tipdocId) {
        this.tipdocId = tipdocId;
    }
    public String getTipdocDescripcion() {
        return this.tipdocDescripcion;
    }
    
    public void setTipdocDescripcion(String tipdocDescripcion) {
        this.tipdocDescripcion = tipdocDescripcion;
    }
    public String getTipdocNombrecorto() {
        return this.tipdocNombrecorto;
    }
    
    public void setTipdocNombrecorto(String tipdocNombrecorto) {
        this.tipdocNombrecorto = tipdocNombrecorto;
    }
    public Date getTipdocFechainicial() {
        return this.tipdocFechainicial;
    }
    
    public void setTipdocFechainicial(Date tipdocFechainicial) {
        this.tipdocFechainicial = tipdocFechainicial;
    }
    public Date getTipdocFechafinal() {
        return this.tipdocFechafinal;
    }
    
    public void setTipdocFechafinal(Date tipdocFechafinal) {
        this.tipdocFechafinal = tipdocFechafinal;
    }
    public BigDecimal getTipdocCodigo() {
        return this.tipdocCodigo;
    }
    
    public void setTipdocCodigo(BigDecimal tipdocCodigo) {
        this.tipdocCodigo = tipdocCodigo;
    }
    public Set getCivPersonases() {
        return this.civPersonases;
    }
    
    public void setCivPersonases(Set civPersonases) {
        this.civPersonases = civPersonases;
    }




}


