package CobroCoactivo.Persistencia;
// Generated 15/06/2018 09:05:14 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * CivTipoDetalleCobro generated by hbm2java
 */
public class CivTipoDetalleCobro  implements java.io.Serializable {


     private BigDecimal tipdetcobId;
     private CivEstadoTipoDetalleCobro civEstadoTipoDetalleCobro;
     private String tipdetcobDescripcion;
     private Date tipdetcobFechaproceso;

    public CivTipoDetalleCobro() {
    }

	
    public CivTipoDetalleCobro(BigDecimal tipdetcobId, CivEstadoTipoDetalleCobro civEstadoTipoDetalleCobro, String tipdetcobDescripcion) {
        this.tipdetcobId = tipdetcobId;
        this.civEstadoTipoDetalleCobro = civEstadoTipoDetalleCobro;
        this.tipdetcobDescripcion = tipdetcobDescripcion;
    }
    public CivTipoDetalleCobro(BigDecimal tipdetcobId, CivEstadoTipoDetalleCobro civEstadoTipoDetalleCobro, String tipdetcobDescripcion, Date tipdetcobFechaproceso) {
       this.tipdetcobId = tipdetcobId;
       this.civEstadoTipoDetalleCobro = civEstadoTipoDetalleCobro;
       this.tipdetcobDescripcion = tipdetcobDescripcion;
       this.tipdetcobFechaproceso = tipdetcobFechaproceso;
    }
   
    public BigDecimal getTipdetcobId() {
        return this.tipdetcobId;
    }
    
    public void setTipdetcobId(BigDecimal tipdetcobId) {
        this.tipdetcobId = tipdetcobId;
    }
    public CivEstadoTipoDetalleCobro getCivEstadoTipoDetalleCobro() {
        return this.civEstadoTipoDetalleCobro;
    }
    
    public void setCivEstadoTipoDetalleCobro(CivEstadoTipoDetalleCobro civEstadoTipoDetalleCobro) {
        this.civEstadoTipoDetalleCobro = civEstadoTipoDetalleCobro;
    }
    public String getTipdetcobDescripcion() {
        return this.tipdetcobDescripcion;
    }
    
    public void setTipdetcobDescripcion(String tipdetcobDescripcion) {
        this.tipdetcobDescripcion = tipdetcobDescripcion;
    }
    public Date getTipdetcobFechaproceso() {
        return this.tipdetcobFechaproceso;
    }
    
    public void setTipdetcobFechaproceso(Date tipdetcobFechaproceso) {
        this.tipdetcobFechaproceso = tipdetcobFechaproceso;
    }




}


