package CobroCoactivo.Persistencia;
// Generated 9/08/2018 03:19:23 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * CivTipoDetalleExpedientes generated by hbm2java
 */
public class CivTipoDetalleExpedientes  implements java.io.Serializable {


     private BigDecimal tipdetexpId;
     private String tidetpexpDescripcion;
     private String tipdetexpNombrecorto;
     private BigDecimal tipdetexpCodigo;
     private Date tipdetexpFechainicial;
     private Date tipdetexpFechafinal;
     private Set civDetalleExpedienteses = new HashSet(0);

    public CivTipoDetalleExpedientes() {
    }

	
    public CivTipoDetalleExpedientes(BigDecimal tipdetexpId, String tidetpexpDescripcion) {
        this.tipdetexpId = tipdetexpId;
        this.tidetpexpDescripcion = tidetpexpDescripcion;
    }
    public CivTipoDetalleExpedientes(BigDecimal tipdetexpId, String tidetpexpDescripcion, String tipdetexpNombrecorto, BigDecimal tipdetexpCodigo, Date tipdetexpFechainicial, Date tipdetexpFechafinal, Set civDetalleExpedienteses) {
       this.tipdetexpId = tipdetexpId;
       this.tidetpexpDescripcion = tidetpexpDescripcion;
       this.tipdetexpNombrecorto = tipdetexpNombrecorto;
       this.tipdetexpCodigo = tipdetexpCodigo;
       this.tipdetexpFechainicial = tipdetexpFechainicial;
       this.tipdetexpFechafinal = tipdetexpFechafinal;
       this.civDetalleExpedienteses = civDetalleExpedienteses;
    }
   
    public BigDecimal getTipdetexpId() {
        return this.tipdetexpId;
    }
    
    public void setTipdetexpId(BigDecimal tipdetexpId) {
        this.tipdetexpId = tipdetexpId;
    }
    public String getTidetpexpDescripcion() {
        return this.tidetpexpDescripcion;
    }
    
    public void setTidetpexpDescripcion(String tidetpexpDescripcion) {
        this.tidetpexpDescripcion = tidetpexpDescripcion;
    }
    public String getTipdetexpNombrecorto() {
        return this.tipdetexpNombrecorto;
    }
    
    public void setTipdetexpNombrecorto(String tipdetexpNombrecorto) {
        this.tipdetexpNombrecorto = tipdetexpNombrecorto;
    }
    public BigDecimal getTipdetexpCodigo() {
        return this.tipdetexpCodigo;
    }
    
    public void setTipdetexpCodigo(BigDecimal tipdetexpCodigo) {
        this.tipdetexpCodigo = tipdetexpCodigo;
    }
    public Date getTipdetexpFechainicial() {
        return this.tipdetexpFechainicial;
    }
    
    public void setTipdetexpFechainicial(Date tipdetexpFechainicial) {
        this.tipdetexpFechainicial = tipdetexpFechainicial;
    }
    public Date getTipdetexpFechafinal() {
        return this.tipdetexpFechafinal;
    }
    
    public void setTipdetexpFechafinal(Date tipdetexpFechafinal) {
        this.tipdetexpFechafinal = tipdetexpFechafinal;
    }
    public Set getCivDetalleExpedienteses() {
        return this.civDetalleExpedienteses;
    }
    
    public void setCivDetalleExpedienteses(Set civDetalleExpedienteses) {
        this.civDetalleExpedienteses = civDetalleExpedienteses;
    }




}


