package CobroCoactivo.Persistencia;
// Generated 27/07/2018 01:43:20 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * CivTipoDetalleCobro generated by hbm2java
 */
public class CivTipoDetalleCobro  implements java.io.Serializable {


     private BigDecimal tipdetcobId;
     private CivEstadoTipoDetalleCobro civEstadoTipoDetalleCobro;
     private String tipdetcobDescripcion;
     private Date tipdetcobFechaproceso;
     private Set civValorTipoDetalleCobros = new HashSet(0);

    public CivTipoDetalleCobro() {
    }

	
    public CivTipoDetalleCobro(BigDecimal tipdetcobId, CivEstadoTipoDetalleCobro civEstadoTipoDetalleCobro, String tipdetcobDescripcion) {
        this.tipdetcobId = tipdetcobId;
        this.civEstadoTipoDetalleCobro = civEstadoTipoDetalleCobro;
        this.tipdetcobDescripcion = tipdetcobDescripcion;
    }
    public CivTipoDetalleCobro(BigDecimal tipdetcobId, CivEstadoTipoDetalleCobro civEstadoTipoDetalleCobro, String tipdetcobDescripcion, Date tipdetcobFechaproceso, Set civValorTipoDetalleCobros) {
       this.tipdetcobId = tipdetcobId;
       this.civEstadoTipoDetalleCobro = civEstadoTipoDetalleCobro;
       this.tipdetcobDescripcion = tipdetcobDescripcion;
       this.tipdetcobFechaproceso = tipdetcobFechaproceso;
       this.civValorTipoDetalleCobros = civValorTipoDetalleCobros;
    }
   
    public BigDecimal getTipdetcobId() {
        return this.tipdetcobId;
    }
    
    public void setTipdetcobId(BigDecimal tipdetcobId) {
        this.tipdetcobId = tipdetcobId;
    }
    public CivEstadoTipoDetalleCobro getCivEstadoTipoDetalleCobro() {
        return this.civEstadoTipoDetalleCobro;
    }
    
    public void setCivEstadoTipoDetalleCobro(CivEstadoTipoDetalleCobro civEstadoTipoDetalleCobro) {
        this.civEstadoTipoDetalleCobro = civEstadoTipoDetalleCobro;
    }
    public String getTipdetcobDescripcion() {
        return this.tipdetcobDescripcion;
    }
    
    public void setTipdetcobDescripcion(String tipdetcobDescripcion) {
        this.tipdetcobDescripcion = tipdetcobDescripcion;
    }
    public Date getTipdetcobFechaproceso() {
        return this.tipdetcobFechaproceso;
    }
    
    public void setTipdetcobFechaproceso(Date tipdetcobFechaproceso) {
        this.tipdetcobFechaproceso = tipdetcobFechaproceso;
    }
    public Set getCivValorTipoDetalleCobros() {
        return this.civValorTipoDetalleCobros;
    }
    
    public void setCivValorTipoDetalleCobros(Set civValorTipoDetalleCobros) {
        this.civValorTipoDetalleCobros = civValorTipoDetalleCobros;
    }




}


