package CobroCoactivo.Persistencia;
// Generated 30/07/2018 08:55:07 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * LogEventos generated by hbm2java
 */
public class LogEventos  implements java.io.Serializable {


     private BigDecimal eveId;
     private CivUsuarios civUsuarios;
     private String eveIp;
     private BigDecimal eveNivel;
     private Date eveFecha;
     private String eveException;
     private String eveMensaje;
     private String eveCausa;
     private String eveClaseOrigen;
     private String eveStacktrace;

    public LogEventos() {
    }

	
    public LogEventos(BigDecimal eveId, CivUsuarios civUsuarios) {
        this.eveId = eveId;
        this.civUsuarios = civUsuarios;
    }
    public LogEventos(BigDecimal eveId, CivUsuarios civUsuarios, String eveIp, BigDecimal eveNivel, Date eveFecha, String eveException, String eveMensaje, String eveCausa, String eveClaseOrigen, String eveStacktrace) {
       this.eveId = eveId;
       this.civUsuarios = civUsuarios;
       this.eveIp = eveIp;
       this.eveNivel = eveNivel;
       this.eveFecha = eveFecha;
       this.eveException = eveException;
       this.eveMensaje = eveMensaje;
       this.eveCausa = eveCausa;
       this.eveClaseOrigen = eveClaseOrigen;
       this.eveStacktrace = eveStacktrace;
    }
   
    public BigDecimal getEveId() {
        return this.eveId;
    }
    
    public void setEveId(BigDecimal eveId) {
        this.eveId = eveId;
    }
    public CivUsuarios getCivUsuarios() {
        return this.civUsuarios;
    }
    
    public void setCivUsuarios(CivUsuarios civUsuarios) {
        this.civUsuarios = civUsuarios;
    }
    public String getEveIp() {
        return this.eveIp;
    }
    
    public void setEveIp(String eveIp) {
        this.eveIp = eveIp;
    }
    public BigDecimal getEveNivel() {
        return this.eveNivel;
    }
    
    public void setEveNivel(BigDecimal eveNivel) {
        this.eveNivel = eveNivel;
    }
    public Date getEveFecha() {
        return this.eveFecha;
    }
    
    public void setEveFecha(Date eveFecha) {
        this.eveFecha = eveFecha;
    }
    public String getEveException() {
        return this.eveException;
    }
    
    public void setEveException(String eveException) {
        this.eveException = eveException;
    }
    public String getEveMensaje() {
        return this.eveMensaje;
    }
    
    public void setEveMensaje(String eveMensaje) {
        this.eveMensaje = eveMensaje;
    }
    public String getEveCausa() {
        return this.eveCausa;
    }
    
    public void setEveCausa(String eveCausa) {
        this.eveCausa = eveCausa;
    }
    public String getEveClaseOrigen() {
        return this.eveClaseOrigen;
    }
    
    public void setEveClaseOrigen(String eveClaseOrigen) {
        this.eveClaseOrigen = eveClaseOrigen;
    }
    public String getEveStacktrace() {
        return this.eveStacktrace;
    }
    
    public void setEveStacktrace(String eveStacktrace) {
        this.eveStacktrace = eveStacktrace;
    }




}


