package CobroCoactivo.Modelo;
// Generated 30/05/2018 02:16:05 PM by Hibernate Tools 4.3.1

import CobroCoactivo.Persistencia.CivAbogados;
import CobroCoactivo.Persistencia.CivEntidades;
import CobroCoactivo.Persistencia.CivEstadoAbogados;
import CobroCoactivo.Persistencia.CivPersonas;
import java.util.Date;

/**
 * Abogados generated by hbm2java
 */
public class Abogados implements java.io.Serializable {

    private int Id;
    private Personas personas;
    private EstadoAbogados estadoAbogados;
    private Entidades entidades;
    private int Numlicencia;
    private Date Fechainicial;
    private Date Fechafinal;
    private String Firma;

    public Abogados(){
    }
    public Abogados(CivAbogados civAbogados, CivPersonas civPersonas, CivEntidades civEntidades) {
        this.Id = civAbogados.getAboId().intValue();
        this.Numlicencia = civAbogados.getAboNumlicencia().intValue();
        this.Fechainicial = civAbogados.getAboFechainicial();
        this.Fechafinal = civAbogados.getAboFechafinal();
        this.Firma = civAbogados.getAboFirma();
        if (civAbogados.getCivEstadoAbogados() != null) {
            this.estadoAbogados = new EstadoAbogados(civAbogados.getCivEstadoAbogados());
        }
        if (civPersonas != null) {
            this.personas = new Personas(civPersonas,civPersonas.getCivEstadoPersonas(),civPersonas.getCivTipoDocumentos(),null);
        }
        if (civEntidades != null) {
            this.entidades = new Entidades(civEntidades,civEntidades.getCivEstadoEntidades(), civEntidades.getCivPersonas());
        }
    }

    /**
     * @return the Id
     */
    public int getId() {
        return Id;
    }

    /**
     * @param Id the Id to set
     */
    public void setId(int Id) {
        this.Id = Id;
    }

    /**
     * @return the personas
     */
    public Personas getPersonas() {
        return personas;
    }

    /**
     * @param personas the personas to set
     */
    public void setPersonas(Personas personas) {
        this.personas = personas;
    }

    /**
     * @return the estadoAbogados
     */
    public EstadoAbogados getEstadoAbogados() {
        return estadoAbogados;
    }

    /**
     * @param estadoAbogados the estadoAbogados to set
     */
    public void setEstadoAbogados(EstadoAbogados estadoAbogados) {
        this.estadoAbogados = estadoAbogados;
    }

    /**
     * @return the entidades
     */
    public Entidades getEntidades() {
        return entidades;
    }

    /**
     * @param entidades the entidades to set
     */
    public void setEntidades(Entidades entidades) {
        this.entidades = entidades;
    }

    /**
     * @return the Numlicencia
     */
    public int getNumlicencia() {
        return Numlicencia;
    }

    /**
     * @param Numlicencia the Numlicencia to set
     */
    public void setNumlicencia(int Numlicencia) {
        this.Numlicencia = Numlicencia;
    }

    /**
     * @return the Fechainicial
     */
    public Date getFechainicial() {
        return Fechainicial;
    }

    /**
     * @param Fechainicial the Fechainicial to set
     */
    public void setFechainicial(Date Fechainicial) {
        this.Fechainicial = Fechainicial;
    }

    /**
     * @return the Fechafinal
     */
    public Date getFechafinal() {
        return Fechafinal;
    }

    /**
     * @param Fechafinal the Fechafinal to set
     */
    public void setFechafinal(Date Fechafinal) {
        this.Fechafinal = Fechafinal;
    }

    /**
     * @return the Firma
     */
    public String getFirma() {
        return Firma;
    }

    /**
     * @param Firma the Firma to set
     */
    public void setFirma(String Firma) {
        this.Firma = Firma;
    }

}
