package CobroCoactivo.Modelo;
// Generated 30/05/2018 02:16:05 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Conceptos generated by hbm2java
 */
public class Conceptos  implements java.io.Serializable {


     private int Id;
     private TipoConceptos tipoConceptos;
     private EstadoConceptos estadoConceptos;
     private String Descripcion;
     private Date Fechaproceso;

    public Conceptos() {
    }

    /**
     * @return the Id
     */
    public int getId() {
        return Id;
    }

    /**
     * @param Id the Id to set
     */
    public void setId(int Id) {
        this.Id = Id;
    }

    /**
     * @return the tipoConceptos
     */
    public TipoConceptos getTipoConceptos() {
        return tipoConceptos;
    }

    /**
     * @param tipoConceptos the tipoConceptos to set
     */
    public void setTipoConceptos(TipoConceptos tipoConceptos) {
        this.tipoConceptos = tipoConceptos;
    }

    /**
     * @return the estadoConceptos
     */
    public EstadoConceptos getEstadoConceptos() {
        return estadoConceptos;
    }

    /**
     * @param estadoConceptos the estadoConceptos to set
     */
    public void setEstadoConceptos(EstadoConceptos estadoConceptos) {
        this.estadoConceptos = estadoConceptos;
    }

    /**
     * @return the Descripcion
     */
    public String getDescripcion() {
        return Descripcion;
    }

    /**
     * @param Descripcion the Descripcion to set
     */
    public void setDescripcion(String Descripcion) {
        this.Descripcion = Descripcion;
    }

    /**
     * @return the Fechaproceso
     */
    public Date getFechaproceso() {
        return Fechaproceso;
    }

    /**
     * @param Fechaproceso the Fechaproceso to set
     */
    public void setFechaproceso(Date Fechaproceso) {
        this.Fechaproceso = Fechaproceso;
    }

	


}


