package CobroCoactivo.Modelo;
// Generated 30/05/2018 02:16:05 PM by Hibernate Tools 4.3.1

import CobroCoactivo.Persistencia.CivConfUsuRec;
import CobroCoactivo.Persistencia.CivEstadoConfusurec;
import CobroCoactivo.Persistencia.CivRecursos;
import CobroCoactivo.Persistencia.CivUsuarios;
import java.util.Date;

/**
 * ConfUsuRec generated by hbm2java
 */
public class ConfUsuRec implements java.io.Serializable {

    private int Id;
    private Usuarios usuarios;
    private Recursos recursos;
    private EstadoConfusurec estadoConfusurec;
    private Date Fechaproceso;
    private boolean selecionado;

    public ConfUsuRec() {
    }

    public ConfUsuRec(CivConfUsuRec civConfUsuRec) {
        this.Id = civConfUsuRec.getConfusurecId().intValue();
        this.Fechaproceso = civConfUsuRec.getConfusurecFechaproceso();
    }

    public ConfUsuRec(CivConfUsuRec civConfUsuRec, CivEstadoConfusurec civEstadoConfusurec) {
        this.Id = civConfUsuRec.getConfusurecId().intValue();
        this.Fechaproceso = civConfUsuRec.getConfusurecFechaproceso();
        this.estadoConfusurec = new EstadoConfusurec(civEstadoConfusurec);
    }

    public ConfUsuRec(CivConfUsuRec civConfUsuRec, CivEstadoConfusurec civEstadoConfusurec, CivUsuarios civUsuarios) {
        this.Id = civConfUsuRec.getConfusurecId().intValue();
        this.Fechaproceso = civConfUsuRec.getConfusurecFechaproceso();
        this.estadoConfusurec = new EstadoConfusurec(civEstadoConfusurec);
        this.usuarios = new Usuarios(civUsuarios);
    }

    public ConfUsuRec(CivConfUsuRec civConfUsuRec, CivEstadoConfusurec civEstadoConfusurec, CivUsuarios civUsuarios, CivRecursos civRecursos) {
        this.Id = civConfUsuRec.getConfusurecId().intValue();
        this.Fechaproceso = civConfUsuRec.getConfusurecFechaproceso();
        this.estadoConfusurec = new EstadoConfusurec(civEstadoConfusurec);
        this.usuarios = new Usuarios(civUsuarios);
        this.recursos = new Recursos(civRecursos);
    }

    /**
     * @return the Id
     */
    public int getConfusurecId() {
        return Id;
    }

    /**
     * @param Id the Id to set
     */
    public void setConfusurecId(int Id) {
        this.Id = Id;
    }

    /**
     * @return the usuarios
     */
    public Usuarios getUsuarios() {
        return usuarios;
    }

    /**
     * @param usuarios the usuarios to set
     */
    public void setUsuarios(Usuarios usuarios) {
        this.usuarios = usuarios;
    }

    /**
     * @return the recursos
     */
    public Recursos getRecursos() {
        return recursos;
    }

    /**
     * @param recursos the recursos to set
     */
    public void setRecursos(Recursos recursos) {
        this.recursos = recursos;
    }

    /**
     * @return the estadoConfusurec
     */
    public EstadoConfusurec getEstadoConfusurec() {
        return estadoConfusurec;
    }

    /**
     * @param estadoConfusurec the estadoConfusurec to set
     */
    public void setEstadoConfusurec(EstadoConfusurec estadoConfusurec) {
        this.estadoConfusurec = estadoConfusurec;
    }

    /**
     * @return the Fechaproceso
     */
    public Date getConfusurecFechaproceso() {
        return Fechaproceso;
    }

    /**
     * @param Fechaproceso the Fechaproceso to set
     */
    public void setConfusurecFechaproceso(Date Fechaproceso) {
        this.Fechaproceso = Fechaproceso;
    }

    /**
     * @return the selecionado
     */
    public boolean isSelecionado() {
        return selecionado;
    }

    /**
     * @param selecionado the selecionado to set
     */
    public void setSelecionado(boolean selecionado) {
        this.selecionado = selecionado;
    }

}
