package CobroCoactivo.Modelo;
// Generated 30/05/2018 02:16:05 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * ConfUsuRec generated by hbm2java
 */
public class ConfUsuRec  implements java.io.Serializable {


     private int Id;
     private Usuarios usuarios;
     private Recursos recursos;
     private EstadoConfusurec estadoConfusurec;
     private Date Fechaproceso;

    public ConfUsuRec() {
    }

    /**
     * @return the Id
     */
    public int getConfusurecId() {
        return Id;
    }

    /**
     * @param Id the Id to set
     */
    public void setConfusurecId(int Id) {
        this.Id = Id;
    }

    /**
     * @return the usuarios
     */
    public Usuarios getUsuarios() {
        return usuarios;
    }

    /**
     * @param usuarios the usuarios to set
     */
    public void setUsuarios(Usuarios usuarios) {
        this.usuarios = usuarios;
    }

    /**
     * @return the recursos
     */
    public Recursos getRecursos() {
        return recursos;
    }

    /**
     * @param recursos the recursos to set
     */
    public void setRecursos(Recursos recursos) {
        this.recursos = recursos;
    }

    /**
     * @return the estadoConfusurec
     */
    public EstadoConfusurec getEstadoConfusurec() {
        return estadoConfusurec;
    }

    /**
     * @param estadoConfusurec the estadoConfusurec to set
     */
    public void setEstadoConfusurec(EstadoConfusurec estadoConfusurec) {
        this.estadoConfusurec = estadoConfusurec;
    }

    /**
     * @return the Fechaproceso
     */
    public Date getConfusurecFechaproceso() {
        return Fechaproceso;
    }

    /**
     * @param Fechaproceso the Fechaproceso to set
     */
    public void setConfusurecFechaproceso(Date Fechaproceso) {
        this.Fechaproceso = Fechaproceso;
    }

}


