package CobroCoactivo.Modelo;
// Generated 30/05/2018 02:16:05 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * DetalleIngresoDeudas generated by hbm2java
 */
public class DetalleIngresoDeudas  implements java.io.Serializable {


     private BigDecimal detingdeuId;
     private IngresoDeudas ingresoDeudas;
     private EstadoDetalleIngresodeu estadoDetalleIngresodeu;
     private Deudas deudas;
     private BigDecimal detingdeuEstdetingdeuFk;
     private Date detingdeuFechaproceso;

    public DetalleIngresoDeudas() {
    }

	
    public DetalleIngresoDeudas(IngresoDeudas ingresoDeudas, EstadoDetalleIngresodeu estadoDetalleIngresodeu, Deudas deudas, BigDecimal detingdeuEstdetingdeuFk) {
        this.ingresoDeudas = ingresoDeudas;
        this.estadoDetalleIngresodeu = estadoDetalleIngresodeu;
        this.deudas = deudas;
        this.detingdeuEstdetingdeuFk = detingdeuEstdetingdeuFk;
    }
    public DetalleIngresoDeudas(IngresoDeudas ingresoDeudas, EstadoDetalleIngresodeu estadoDetalleIngresodeu, Deudas deudas, BigDecimal detingdeuEstdetingdeuFk, Date detingdeuFechaproceso) {
       this.ingresoDeudas = ingresoDeudas;
       this.estadoDetalleIngresodeu = estadoDetalleIngresodeu;
       this.deudas = deudas;
       this.detingdeuEstdetingdeuFk = detingdeuEstdetingdeuFk;
       this.detingdeuFechaproceso = detingdeuFechaproceso;
    }
   
    public BigDecimal getDetingdeuId() {
        return this.detingdeuId;
    }
    
    public void setDetingdeuId(BigDecimal detingdeuId) {
        this.detingdeuId = detingdeuId;
    }
    public IngresoDeudas getIngresoDeudas() {
        return this.ingresoDeudas;
    }
    
    public void setIngresoDeudas(IngresoDeudas ingresoDeudas) {
        this.ingresoDeudas = ingresoDeudas;
    }
    public EstadoDetalleIngresodeu getEstadoDetalleIngresodeu() {
        return this.estadoDetalleIngresodeu;
    }
    
    public void setEstadoDetalleIngresodeu(EstadoDetalleIngresodeu estadoDetalleIngresodeu) {
        this.estadoDetalleIngresodeu = estadoDetalleIngresodeu;
    }
    public Deudas getDeudas() {
        return this.deudas;
    }
    
    public void setDeudas(Deudas deudas) {
        this.deudas = deudas;
    }
    public BigDecimal getDetingdeuEstdetingdeuFk() {
        return this.detingdeuEstdetingdeuFk;
    }
    
    public void setDetingdeuEstdetingdeuFk(BigDecimal detingdeuEstdetingdeuFk) {
        this.detingdeuEstdetingdeuFk = detingdeuEstdetingdeuFk;
    }
    public Date getDetingdeuFechaproceso() {
        return this.detingdeuFechaproceso;
    }
    
    public void setDetingdeuFechaproceso(Date detingdeuFechaproceso) {
        this.detingdeuFechaproceso = detingdeuFechaproceso;
    }




}


