package CobroCoactivo.Modelo;
// Generated 30/05/2018 02:16:05 PM by Hibernate Tools 4.3.1

import CobroCoactivo.Persistencia.CivDetalleExpedientes;
import CobroCoactivo.Persistencia.CivDeudas;
import CobroCoactivo.Persistencia.CivEstadoDetalleExpedientes;
import CobroCoactivo.Persistencia.CivExpedientes;
import CobroCoactivo.Persistencia.CivTipoDetalleExpedientes;
import java.util.Date;

/**
 * DetalleExpedientes generated by hbm2java
 */
public class DetalleExpedientes implements java.io.Serializable {

    private int Id;
    private TipoDetalleExpedientes tipoDetalleExpedientes;
    private Expedientes expedientes;
    private EstadoDetalleExpedientes estadoDetalleExpedientes;
    private Deudas deudas;
    private String Descripcion;
    private String ubicacion;
    private Date Fechaproceso;
    private boolean selecionado;

    public DetalleExpedientes() {
    }

    public DetalleExpedientes(CivDetalleExpedientes civDetalleExpedientes) {
        this.Id = civDetalleExpedientes.getDetexpId().intValue();
        this.Descripcion = civDetalleExpedientes.getDetexpDescripcion();
        this.Fechaproceso = civDetalleExpedientes.getDetexpFechaproceso();
    }

    public DetalleExpedientes(CivDetalleExpedientes civDetalleExpedientes, CivExpedientes civExpedientes) {
        this.Id = civDetalleExpedientes.getDetexpId().intValue();
        this.Descripcion = civDetalleExpedientes.getDetexpDescripcion();
        this.Fechaproceso = civDetalleExpedientes.getDetexpFechaproceso();
        this.expedientes = new Expedientes(civExpedientes);
    }

    public DetalleExpedientes(CivDetalleExpedientes civDetalleExpedientes, CivExpedientes civExpedientes, CivEstadoDetalleExpedientes civEstadoDetalleExpedientes) {
        this.Id = civDetalleExpedientes.getDetexpId().intValue();
        this.Descripcion = civDetalleExpedientes.getDetexpDescripcion();
        this.Fechaproceso = civDetalleExpedientes.getDetexpFechaproceso();
        this.expedientes = new Expedientes(civExpedientes);
        this.estadoDetalleExpedientes = new EstadoDetalleExpedientes(civEstadoDetalleExpedientes);
    }

    public DetalleExpedientes(CivDetalleExpedientes civDetalleExpedientes, CivExpedientes civExpedientes, CivEstadoDetalleExpedientes civEstadoDetalleExpedientes, CivTipoDetalleExpedientes civTipoDetalleExpedientes) {
        this.Id = civDetalleExpedientes.getDetexpId().intValue();
        this.Descripcion = civDetalleExpedientes.getDetexpDescripcion();
        this.Fechaproceso = civDetalleExpedientes.getDetexpFechaproceso();
        this.expedientes = new Expedientes(civExpedientes);
        this.estadoDetalleExpedientes = new EstadoDetalleExpedientes(civEstadoDetalleExpedientes);
        this.tipoDetalleExpedientes = new TipoDetalleExpedientes(civTipoDetalleExpedientes);
    }

    public DetalleExpedientes(CivDetalleExpedientes civDetalleExpedientes, CivExpedientes civExpedientes, CivEstadoDetalleExpedientes civEstadoDetalleExpedientes, CivTipoDetalleExpedientes civTipoDetalleExpedientes, CivDeudas civDeudas) {
        this.Id = civDetalleExpedientes.getDetexpId().intValue();
        this.Descripcion = civDetalleExpedientes.getDetexpDescripcion();
        this.Fechaproceso = civDetalleExpedientes.getDetexpFechaproceso();
        this.expedientes = new Expedientes(civExpedientes);
        this.estadoDetalleExpedientes = new EstadoDetalleExpedientes(civEstadoDetalleExpedientes);
        this.tipoDetalleExpedientes = new TipoDetalleExpedientes(civTipoDetalleExpedientes);
        this.deudas = new Deudas(civDeudas);
    }

    public int getDetexpId() {
        return this.Id;
    }

    public void setDetexpId(int Id) {
        this.Id = Id;
    }

    public TipoDetalleExpedientes getTipoDetalleExpedientes() {
        return this.tipoDetalleExpedientes;
    }

    public void setTipoDetalleExpedientes(TipoDetalleExpedientes tipoDetalleExpedientes) {
        this.tipoDetalleExpedientes = tipoDetalleExpedientes;
    }

    public Expedientes getExpedientes() {
        return this.expedientes;
    }

    public void setExpedientes(Expedientes expedientes) {
        this.expedientes = expedientes;
    }

    public EstadoDetalleExpedientes getEstadoDetalleExpedientes() {
        return this.estadoDetalleExpedientes;
    }

    public void setEstadoDetalleExpedientes(EstadoDetalleExpedientes estadoDetalleExpedientes) {
        this.estadoDetalleExpedientes = estadoDetalleExpedientes;
    }

    public String getDetexpDescripcion() {
        return this.Descripcion;
    }

    public void setDetexpDescripcion(String Descripcion) {
        this.Descripcion = Descripcion;
    }

    public Date getDetexpFechaproceso() {
        return this.Fechaproceso;
    }

    public void setDetexpFechaproceso(Date Fechaproceso) {
        this.Fechaproceso = Fechaproceso;
    }

    /**
     * @return the deudas
     */
    public Deudas getDeudas() {
        return deudas;
    }

    /**
     * @param deudas the deudas to set
     */
    public void setDeudas(Deudas deudas) {
        this.deudas = deudas;
    }

    /**
     * @return the ubicacion
     */
    public String getUbicacion() {
        return ubicacion;
    }

    /**
     * @param ubicacion the ubicacion to set
     */
    public void setUbicacion(String ubicacion) {
        this.ubicacion = ubicacion;
    }

    /**
     * @return the selecionado
     */
    public boolean isSelecionado() {
        return selecionado;
    }

    /**
     * @param selecionado the selecionado to set
     */
    public void setSelecionado(boolean selecionado) {
        this.selecionado = selecionado;
    }

}
