package CobroCoactivo.Modelo;
// Generated 30/05/2018 02:16:05 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * DetalleExpedientes generated by hbm2java
 */
public class DetalleExpedientes  implements java.io.Serializable {


     private BigDecimal detexpId;
     private TipoDetalleExpedientes tipoDetalleExpedientes;
     private Expedientes expedientes;
     private EstadoDetalleExpedientes estadoDetalleExpedientes;
     private String detexpDescripcion;
     private Date detexpFechaproceso;

    public DetalleExpedientes() {
    }

	
    public DetalleExpedientes(BigDecimal detexpId, TipoDetalleExpedientes tipoDetalleExpedientes, Expedientes expedientes, EstadoDetalleExpedientes estadoDetalleExpedientes, String detexpDescripcion) {
        this.detexpId = detexpId;
        this.tipoDetalleExpedientes = tipoDetalleExpedientes;
        this.expedientes = expedientes;
        this.estadoDetalleExpedientes = estadoDetalleExpedientes;
        this.detexpDescripcion = detexpDescripcion;
    }
    public DetalleExpedientes(BigDecimal detexpId, TipoDetalleExpedientes tipoDetalleExpedientes, Expedientes expedientes, EstadoDetalleExpedientes estadoDetalleExpedientes, String detexpDescripcion, Date detexpFechaproceso) {
       this.detexpId = detexpId;
       this.tipoDetalleExpedientes = tipoDetalleExpedientes;
       this.expedientes = expedientes;
       this.estadoDetalleExpedientes = estadoDetalleExpedientes;
       this.detexpDescripcion = detexpDescripcion;
       this.detexpFechaproceso = detexpFechaproceso;
    }
   
    public BigDecimal getDetexpId() {
        return this.detexpId;
    }
    
    public void setDetexpId(BigDecimal detexpId) {
        this.detexpId = detexpId;
    }
    public TipoDetalleExpedientes getTipoDetalleExpedientes() {
        return this.tipoDetalleExpedientes;
    }
    
    public void setTipoDetalleExpedientes(TipoDetalleExpedientes tipoDetalleExpedientes) {
        this.tipoDetalleExpedientes = tipoDetalleExpedientes;
    }
    public Expedientes getExpedientes() {
        return this.expedientes;
    }
    
    public void setExpedientes(Expedientes expedientes) {
        this.expedientes = expedientes;
    }
    public EstadoDetalleExpedientes getEstadoDetalleExpedientes() {
        return this.estadoDetalleExpedientes;
    }
    
    public void setEstadoDetalleExpedientes(EstadoDetalleExpedientes estadoDetalleExpedientes) {
        this.estadoDetalleExpedientes = estadoDetalleExpedientes;
    }
    public String getDetexpDescripcion() {
        return this.detexpDescripcion;
    }
    
    public void setDetexpDescripcion(String detexpDescripcion) {
        this.detexpDescripcion = detexpDescripcion;
    }
    public Date getDetexpFechaproceso() {
        return this.detexpFechaproceso;
    }
    
    public void setDetexpFechaproceso(Date detexpFechaproceso) {
        this.detexpFechaproceso = detexpFechaproceso;
    }




}


