package CobroCoactivo.Modelo;
// Generated 30/05/2018 02:16:05 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * DetalleDeudas generated by hbm2java
 */
public class DetalleDeudas  implements java.io.Serializable {


     private BigDecimal detdeuId;
     private EstadoDetalleDeudas estadoDetalleDeudas;
     private Deudas deudas;
     private Conceptos conceptos;
     private BigDecimal deuValor;
     private Date deuFechaproceso;

    public DetalleDeudas() {
    }

	
    public DetalleDeudas(BigDecimal detdeuId, EstadoDetalleDeudas estadoDetalleDeudas, Deudas deudas, Conceptos conceptos) {
        this.detdeuId = detdeuId;
        this.estadoDetalleDeudas = estadoDetalleDeudas;
        this.deudas = deudas;
        this.conceptos = conceptos;
    }
    public DetalleDeudas(BigDecimal detdeuId, EstadoDetalleDeudas estadoDetalleDeudas, Deudas deudas, Conceptos conceptos, BigDecimal deuValor, Date deuFechaproceso) {
       this.detdeuId = detdeuId;
       this.estadoDetalleDeudas = estadoDetalleDeudas;
       this.deudas = deudas;
       this.conceptos = conceptos;
       this.deuValor = deuValor;
       this.deuFechaproceso = deuFechaproceso;
    }
   
    public BigDecimal getDetdeuId() {
        return this.detdeuId;
    }
    
    public void setDetdeuId(BigDecimal detdeuId) {
        this.detdeuId = detdeuId;
    }
    public EstadoDetalleDeudas getEstadoDetalleDeudas() {
        return this.estadoDetalleDeudas;
    }
    
    public void setEstadoDetalleDeudas(EstadoDetalleDeudas estadoDetalleDeudas) {
        this.estadoDetalleDeudas = estadoDetalleDeudas;
    }
    public Deudas getDeudas() {
        return this.deudas;
    }
    
    public void setDeudas(Deudas deudas) {
        this.deudas = deudas;
    }
    public Conceptos getConceptos() {
        return this.conceptos;
    }
    
    public void setConceptos(Conceptos conceptos) {
        this.conceptos = conceptos;
    }
    public BigDecimal getDeuValor() {
        return this.deuValor;
    }
    
    public void setDeuValor(BigDecimal deuValor) {
        this.deuValor = deuValor;
    }
    public Date getDeuFechaproceso() {
        return this.deuFechaproceso;
    }
    
    public void setDeuFechaproceso(Date deuFechaproceso) {
        this.deuFechaproceso = deuFechaproceso;
    }




}


