package CobroCoactivo.Modelo;
// Generated 30/05/2018 02:16:05 PM by Hibernate Tools 4.3.1

import CobroCoactivo.Persistencia.CivCobroDeudas;
import CobroCoactivo.Persistencia.CivDetalleExpedientes;
import CobroCoactivo.Persistencia.CivDeudas;
import CobroCoactivo.Persistencia.CivEstadoDeudas;
import CobroCoactivo.Persistencia.CivMovimientos;
import CobroCoactivo.Persistencia.CivPersonas;
import CobroCoactivo.Persistencia.CivPlanTrabajos;
import CobroCoactivo.Persistencia.CivTipoDeudas;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

/**
 * Deudas generated by hbm2java
 */
public class Deudas implements java.io.Serializable {

    private int Id;
    private Date FechaDeudas;
    private int Valor;
    private int Saldo;
    private Date Fechaproceso;
    private String Referencia;
    private double cobroFacil;
    private double cobroMediano;
    private double cobroDificil;
    private boolean seleccionado;
    private EstadoDeudas estadoDeudas;
    private PlanTrabajos planTrabajoDeuda;
    private TipoDeudas tipoDeudas;
    private Personas personas;
    private CobroDeudas cobroDeudas;
    private int diasHabilesDeuda;
    private long referenciaUnica;
    // Lista que se utilizara para listar los movimeindo de la deuda seleccionada.
    private List<Movimientos> listMovimientos = new ArrayList<>();

    public Deudas() {
    }

    public Deudas(CivDeudas civDeudas) {
        this.Id = civDeudas.getDeuId().intValue();
        this.FechaDeudas = civDeudas.getDeuFechadeuda();
        this.Valor = civDeudas.getDeuValor().intValue();
        this.Saldo = civDeudas.getDeuSaldo().intValue();
        this.Fechaproceso = civDeudas.getDeuFechaproceso();
        this.Referencia = civDeudas.getDeuReferencia();
        this.referenciaUnica = civDeudas.getDeuRefUnica().longValue();

    }

    public Deudas(CivDeudas civDeudas, CivEstadoDeudas civEstadoDeudas) {
        this.Id = civDeudas.getDeuId().intValue();
        this.FechaDeudas = civDeudas.getDeuFechadeuda();
        this.Valor = civDeudas.getDeuValor().intValue();
        this.Saldo = civDeudas.getDeuSaldo().intValue();
        this.Fechaproceso = civDeudas.getDeuFechaproceso();
        this.Referencia = civDeudas.getDeuReferencia();
        this.estadoDeudas = new EstadoDeudas(civEstadoDeudas);
    }

    public Deudas(CivDeudas civDeudas, CivEstadoDeudas civEstadoDeudas, CivPlanTrabajos civPlanTrabajos) {
        this.Id = civDeudas.getDeuId().intValue();
        this.FechaDeudas = civDeudas.getDeuFechadeuda();
        this.Valor = civDeudas.getDeuValor().intValue();
        this.Saldo = civDeudas.getDeuSaldo().intValue();
        this.Fechaproceso = civDeudas.getDeuFechaproceso();
        this.Referencia = civDeudas.getDeuReferencia();
        this.estadoDeudas = new EstadoDeudas(civEstadoDeudas);
        this.planTrabajoDeuda = new PlanTrabajos(civPlanTrabajos);

    }

    public Deudas(CivDeudas civDeudas, CivEstadoDeudas civEstadoDeudas, CivPlanTrabajos civPlanTrabajos, CivTipoDeudas civTipoDeudas) {
        this.Id = civDeudas.getDeuId().intValue();
        this.FechaDeudas = civDeudas.getDeuFechadeuda();
        this.Valor = civDeudas.getDeuValor().intValue();
        this.Saldo = civDeudas.getDeuSaldo().intValue();
        this.Fechaproceso = civDeudas.getDeuFechaproceso();
        this.Referencia = civDeudas.getDeuReferencia();
        this.estadoDeudas = new EstadoDeudas(civEstadoDeudas);
        this.tipoDeudas = new TipoDeudas(civTipoDeudas);
        this.planTrabajoDeuda = new PlanTrabajos(civPlanTrabajos);

    }

    public Deudas(CivDeudas civDeudas, CivEstadoDeudas civEstadoDeudas, CivPlanTrabajos civPlanTrabajos, CivTipoDeudas civTipoDeudas, CivPersonas civPersonas) {
        this.Id = civDeudas.getDeuId().intValue();
        this.FechaDeudas = civDeudas.getDeuFechadeuda();
        this.Valor = civDeudas.getDeuValor().intValue();
        this.Saldo = civDeudas.getDeuSaldo().intValue();
        this.Fechaproceso = civDeudas.getDeuFechaproceso();
        this.Referencia = civDeudas.getDeuReferencia();
        this.estadoDeudas = new EstadoDeudas(civEstadoDeudas);
        this.planTrabajoDeuda = new PlanTrabajos(civPlanTrabajos);
        this.tipoDeudas = new TipoDeudas(civTipoDeudas);
        this.personas = new Personas(civPersonas, civPersonas.getCivTipoDocumentos());
    }

    public Deudas(CivDeudas civDeudas, CivEstadoDeudas civEstadoDeudas, CivPlanTrabajos civPlanTrabajos, CivTipoDeudas civTipoDeudas, CivPersonas civPersonas, CivCobroDeudas civCobroDeudas) {
        this.Id = civDeudas.getDeuId().intValue();
        this.FechaDeudas = civDeudas.getDeuFechadeuda();
        this.Valor = civDeudas.getDeuValor().intValue();
        this.Saldo = civDeudas.getDeuSaldo().intValue();
        this.Fechaproceso = civDeudas.getDeuFechaproceso();
        this.Referencia = civDeudas.getDeuReferencia();
        this.estadoDeudas = new EstadoDeudas(civEstadoDeudas);
        this.tipoDeudas = new TipoDeudas(civTipoDeudas);
        this.personas = new Personas(civPersonas, civPersonas.getCivTipoDocumentos());
        this.planTrabajoDeuda = new PlanTrabajos(civPlanTrabajos);
        if (civCobroDeudas != null) {
            this.cobroDeudas = new CobroDeudas(civCobroDeudas);
        }

    }

    public Deudas(CivDeudas civDeudas, CivEstadoDeudas civEstadoDeudas, CivPlanTrabajos civPlanTrabajos, CivTipoDeudas civTipoDeudas, CivPersonas civPersonas, CivCobroDeudas civCobroDeudas, List<CivMovimientos> listCivMovimientos) {
        this.Id = civDeudas.getDeuId().intValue();
        this.FechaDeudas = civDeudas.getDeuFechadeuda();
        this.Valor = civDeudas.getDeuValor().intValue();
        this.Saldo = civDeudas.getDeuSaldo().intValue();
        this.Fechaproceso = civDeudas.getDeuFechaproceso();
        this.Referencia = civDeudas.getDeuReferencia();
        this.estadoDeudas = new EstadoDeudas(civEstadoDeudas);
        this.planTrabajoDeuda = new PlanTrabajos(civPlanTrabajos);
        this.tipoDeudas = new TipoDeudas(civTipoDeudas);
        this.cobroDeudas = new CobroDeudas(civCobroDeudas);
        this.personas = new Personas(civPersonas, civPersonas.getCivEstadoPersonas(), civPersonas.getCivTipoDocumentos());
        for (CivMovimientos civMovimientos : listCivMovimientos) {
            Movimientos movimientos = new Movimientos(civMovimientos, civMovimientos.getCivEstadoMovimientos(), civDeudas, civMovimientos.getCivFasesTrabajos(), civPersonas, civMovimientos.getCivUsuarios());
            this.listMovimientos.add(movimientos);
        }
    }

    /**
     * @return the Id
     */
    public int getId() {
        return Id;
    }

    /**
     * @param Id the Id to set
     */
    public void setId(int Id) {
        this.Id = Id;
    }

    /**
     * @return the tipoDeudas
     */
    public TipoDeudas getTipoDeudas() {
        return tipoDeudas;
    }

    /**
     * @param tipoDeudas the tipoDeudas to set
     */
    public void setTipoDeudas(TipoDeudas tipoDeudas) {
        this.tipoDeudas = tipoDeudas;
    }

    /**
     * @return the personas
     */
    public Personas getPersonas() {
        return personas;
    }

    /**
     * @param personas the personas to set
     */
    public void setPersonas(Personas personas) {
        this.personas = personas;
    }

    /**
     * @return the estadoDeudas
     */
    public EstadoDeudas getEstadoDeudas() {
        return estadoDeudas;
    }

    /**
     * @param estadoDeudas the estadoDeudas to set
     */
    public void setEstadoDeudas(EstadoDeudas estadoDeudas) {
        this.estadoDeudas = estadoDeudas;
    }

    /**
     * @return the Valor
     */
    public int getValor() {
        return Valor;
    }

    /**
     * @param Valor the Valor to set
     */
    public void setValor(int Valor) {
        this.Valor = Valor;
    }

    /**
     * @return the Saldo
     */
    public int getSaldo() {
        return Saldo;
    }

    /**
     * @param Saldo the Saldo to set
     */
    public void setSaldo(int Saldo) {
        this.Saldo = Saldo;
    }

    /**
     * @return the Fechaproceso
     */
    public Date getFechaproceso() {
        return Fechaproceso;
    }

    /**
     * @param Fechaproceso the Fechaproceso to set
     */
    public void setFechaproceso(Date Fechaproceso) {
        this.Fechaproceso = Fechaproceso;
    }

    /**
     * @return the FechaDeudas
     */
    public Date getFechaDeudas() {
        return FechaDeudas;
    }

    /**
     * @param FechaDeudas the FechaDeudas to set
     */
    public void setFechaDeudas(Date FechaDeudas) {
        this.FechaDeudas = FechaDeudas;
    }

    /**
     * @return the Referencia
     */
    public String getReferencia() {
        return Referencia;
    }

    /**
     * @param Referencia the Referencia to set
     */
    public void setReferencia(String Referencia) {
        this.Referencia = Referencia;
    }

    /**
     * @return the cobroFacil
     */
    public double getCobroFacil() {
        return cobroFacil;
    }

    /**
     * @param cobroFacil the cobroFacil to set
     */
    public void setCobroFacil(double cobroFacil) {
        this.cobroFacil = cobroFacil;
    }

    /**
     * @return the cobroMediano
     */
    public double getCobroMediano() {
        return cobroMediano;
    }

    /**
     * @param cobroMediano the cobroMediano to set
     */
    public void setCobroMediano(double cobroMediano) {
        this.cobroMediano = cobroMediano;
    }

    /**
     * @return the cobroDificil
     */
    public double getCobroDificil() {
        return cobroDificil;
    }

    /**
     * @param cobroDificil the cobroDificil to set
     */
    public void setCobroDificil(double cobroDificil) {
        this.cobroDificil = cobroDificil;
    }

    /**
     * @return the cobroDeudas
     */
    public CobroDeudas getCobroDeudas() {
        return cobroDeudas;
    }

    /**
     * @param cobroDeudas the cobroDeudas to set
     */
    public void setCobroDeudas(CobroDeudas cobroDeudas) {
        this.cobroDeudas = cobroDeudas;
    }

    /**
     * @return the seleccionado
     */
    public boolean isSeleccionado() {
        return seleccionado;
    }

    /**
     * @param seleccionado the seleccionado to set
     */
    public void setSeleccionado(boolean seleccionado) {
        this.seleccionado = seleccionado;
    }

    /**
     * @return the planTrabajoDeuda
     */
    public PlanTrabajos getPlanTrabajoDeuda() {
        return planTrabajoDeuda;
    }

    /**
     * @param planTrabajoDeuda the planTrabajoDeuda to set
     */
    public void setPlanTrabajoDeuda(PlanTrabajos planTrabajoDeuda) {
        this.planTrabajoDeuda = planTrabajoDeuda;
    }

    /**
     * @return the diasHabilesDeuda
     */
    public int getDiasHabilesDeuda() {
        return diasHabilesDeuda;
    }

    /**
     * @param diasHabilesDeuda the diasHabilesDeuda to set
     */
    public void setDiasHabilesDeuda(int diasHabilesDeuda) {
        this.diasHabilesDeuda = diasHabilesDeuda;
    }

    /**
     * @return the listMovimientos
     */
    public List<Movimientos> getListMovimientos() {
        return listMovimientos;
    }

    /**
     * @param listMovimientos the listMovimientos to set
     */
    public void setListMovimientos(List<Movimientos> listMovimientos) {
        this.listMovimientos = listMovimientos;
    }

    /**
     * @return the referenciaUnica
     */
    public long getReferenciaUnica() {
        return referenciaUnica;
    }

    /**
     * @param referenciaUnica the referenciaUnica to set
     */
    public void setReferenciaUnica(long referenciaUnica) {
        this.referenciaUnica = referenciaUnica;
    }

}
