package CobroCoactivo.Modelo;
// Generated 30/05/2018 02:16:05 PM by Hibernate Tools 4.3.1

import CobroCoactivo.Persistencia.CivDeudas;
import CobroCoactivo.Persistencia.CivEstadoDeudas;
import CobroCoactivo.Persistencia.CivPersonas;
import CobroCoactivo.Persistencia.CivTipoDeudas;
import java.util.Date;

/**
 * Deudas generated by hbm2java
 */
public class Deudas implements java.io.Serializable {

    private int Id;
    private TipoDeudas tipoDeudas;
    private Personas personas;
    private EstadoDeudas estadoDeudas;
    private Date Fechada;
    private int Valor;
    private int Saldo;
    private Date Fechaproceso;

    public Deudas() {
    }

    public Deudas(CivDeudas civDeudas) {
        this.Id = civDeudas.getDeuId().intValue();
        this.Fechada = civDeudas.getDeuFechadeuda();
        this.Valor = civDeudas.getDeuValor().intValue();
        this.Saldo = civDeudas.getDeuSaldo().intValue();
        this.Fechaproceso = civDeudas.getDeuFechaproceso();
    }

    public Deudas(CivDeudas civDeudas, CivEstadoDeudas civEstadoDeudas, CivTipoDeudas civTipoDeudas) {
        this.Id = civDeudas.getDeuId().intValue();
        this.Fechada = civDeudas.getDeuFechadeuda();
        this.Valor = civDeudas.getDeuValor().intValue();
        this.Saldo = civDeudas.getDeuSaldo().intValue();
        this.Fechaproceso = civDeudas.getDeuFechaproceso();
        //this.estadoDeudas = new EstadoDeudas(civEstadoDeudas);
        this.tipoDeudas = new TipoDeudas(civTipoDeudas);

    }

    public Deudas(CivDeudas civDeudas, CivEstadoDeudas civEstadoDeudas, CivTipoDeudas civTipoDeudas,CivPersonas civPersonas) {
        this.Id = civDeudas.getDeuId().intValue();
        this.Fechada = civDeudas.getDeuFechadeuda();
        this.Valor = civDeudas.getDeuValor().intValue();
        this.Saldo = civDeudas.getDeuSaldo().intValue();
        this.Fechaproceso = civDeudas.getDeuFechaproceso();
        //this.estadoDeudas = new EstadoDeudas(civEstadoDeudas);
        this.tipoDeudas = new TipoDeudas(civTipoDeudas);
        this.personas = new Personas(civPersonas,civPersonas.getCivEstadoPersonas(), civPersonas.getCivTipoDocumentos());
    }

    /**
     * @return the Id
     */
    public int getId() {
        return Id;
    }

    /**
     * @param Id the Id to set
     */
    public void setId(int Id) {
        this.Id = Id;
    }

    /**
     * @return the tipoDeudas
     */
    public TipoDeudas getTipoDeudas() {
        return tipoDeudas;
    }

    /**
     * @param tipoDeudas the tipoDeudas to set
     */
    public void setTipoDeudas(TipoDeudas tipoDeudas) {
        this.tipoDeudas = tipoDeudas;
    }

    /**
     * @return the personas
     */
    public Personas getPersonas() {
        return personas;
    }

    /**
     * @param personas the personas to set
     */
    public void setPersonas(Personas personas) {
        this.personas = personas;
    }

    /**
     * @return the estadoDeudas
     */
    public EstadoDeudas getEstadoDeudas() {
        return estadoDeudas;
    }

    /**
     * @param estadoDeudas the estadoDeudas to set
     */
    public void setEstadoDeudas(EstadoDeudas estadoDeudas) {
        this.estadoDeudas = estadoDeudas;
    }

    /**
     * @return the Fechada
     */
    public Date getFechada() {
        return Fechada;
    }

    /**
     * @param Fechada the Fechada to set
     */
    public void setFechada(Date Fechada) {
        this.Fechada = Fechada;
    }

    /**
     * @return the Valor
     */
    public int getValor() {
        return Valor;
    }

    /**
     * @param Valor the Valor to set
     */
    public void setValor(int Valor) {
        this.Valor = Valor;
    }

    /**
     * @return the Saldo
     */
    public int getSaldo() {
        return Saldo;
    }

    /**
     * @param Saldo the Saldo to set
     */
    public void setSaldo(int Saldo) {
        this.Saldo = Saldo;
    }

    /**
     * @return the Fechaproceso
     */
    public Date getFechaproceso() {
        return Fechaproceso;
    }

    /**
     * @param Fechaproceso the Fechaproceso to set
     */
    public void setFechaproceso(Date Fechaproceso) {
        this.Fechaproceso = Fechaproceso;
    }

}
