package CobroCoactivo.Modelo;
// Generated 30/05/2018 02:16:05 PM by Hibernate Tools 4.3.1


import CobroCoactivo.Persistencia.CivDocumenGenerales;
import CobroCoactivo.Persistencia.CivEstadoDocumengenerales;
import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * DocumenGenerales generated by hbm2java
 */
public class DocumenGenerales  implements java.io.Serializable {


     private int id;
     private EstadoDocumengenerales estadoDocumengenerales;
     private String descripcion;
     private Date fechaproceso;
     private String archivo;

    public DocumenGenerales() {
    }

	
    public DocumenGenerales(CivDocumenGenerales civDocumenGenerales) {
        this.id = civDocumenGenerales.getDocgenId().intValue();
        this.descripcion = civDocumenGenerales.getDocgenDescripcion();
        this.fechaproceso = civDocumenGenerales.getDocgenFechaproceso();
        this.archivo = civDocumenGenerales.getDocgenArchivo();
    }
    public DocumenGenerales(CivDocumenGenerales civDocumenGenerales,CivEstadoDocumengenerales civEstadoDocumengenerales) {
        this.id = civDocumenGenerales.getDocgenId().intValue();
        this.descripcion = civDocumenGenerales.getDocgenDescripcion();
        this.fechaproceso = civDocumenGenerales.getDocgenFechaproceso();
        this.archivo = civDocumenGenerales.getDocgenArchivo();
        this.estadoDocumengenerales = new EstadoDocumengenerales(civEstadoDocumengenerales);
    }

    /**
     * @return the Id
     */
    public int getId() {
        return id;
    }

    /**
     * @param Id the Id to set
     */
    public void setId(int Id) {
        this.id = Id;
    }

    /**
     * @return the estadoDocumengenerales
     */
    public EstadoDocumengenerales getEstadoDocumengenerales() {
        return estadoDocumengenerales;
    }

    /**
     * @param estadoDocumengenerales the estadoDocumengenerales to set
     */
    public void setEstadoDocumengenerales(EstadoDocumengenerales estadoDocumengenerales) {
        this.estadoDocumengenerales = estadoDocumengenerales;
    }

    /**
     * @return the Descripcion
     */
    public String getDescripcion() {
        return descripcion;
    }

    /**
     * @param Descripcion the Descripcion to set
     */
    public void setDescripcion(String Descripcion) {
        this.descripcion = Descripcion;
    }

    /**
     * @return the Fechaproceso
     */
    public Date getFechaproceso() {
        return fechaproceso;
    }

    /**
     * @param Fechaproceso the Fechaproceso to set
     */
    public void setFechaproceso(Date Fechaproceso) {
        this.fechaproceso = Fechaproceso;
    }

    /**
     * @return the Archivo
     */
    public String getArchivo() {
        return archivo;
    }

    /**
     * @param Archivo the Archivo to set
     */
    public void setArchivo(String Archivo) {
        this.archivo = Archivo;
    }

}


