package CobroCoactivo.Modelo;
// Generated 30/05/2018 02:16:05 PM by Hibernate Tools 4.3.1

import CobroCoactivo.Persistencia.CivEntidades;
import CobroCoactivo.Persistencia.CivEstadoEntidades;
import CobroCoactivo.Persistencia.CivPersonas;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

/**
 * Entidades generated by hbm2java
 */
public class Entidades implements java.io.Serializable {

    private int Id;
    private Personas personas;
    private EstadoEntidades estadoEntidades;
    private Date Fechaproceso;
    private List listAbogados = new ArrayList<>();

    public Entidades() {
    }

    public Entidades(CivEntidades civEntidades) {
        this.Id = civEntidades.getEntId().intValue();
        this.Fechaproceso = civEntidades.getEntFechaproceso();
    }

    public Entidades(CivEntidades civEntidades, CivEstadoEntidades civEstadoEntidades) {
        this.Id = civEntidades.getEntId().intValue();
        this.Fechaproceso = civEntidades.getEntFechaproceso();
        //this.estadoEntidades = new EstadoEntidades(civEstadoEntidades);
    }

    public Entidades(CivEntidades civEntidades, CivEstadoEntidades civEstadoEntidades,CivPersonas civPersonas) {
        this.Id = civEntidades.getEntId().intValue();
        this.Fechaproceso = civEntidades.getEntFechaproceso();
        //this.estadoEntidades = new EstadoEntidades(civEstadoEntidades);
        this.personas = new Personas(civPersonas, civPersonas.getCivEstadoPersonas(), civPersonas.getCivTipoDocumentos(), null);
       
    }
    
    

    /**
     * @return the Id
     */
    public int getEntId() {
        return Id;
    }

    /**
     * @param Id the Id to set
     */
    public void setEntId(int Id) {
        this.Id = Id;
    }

    /**
     * @return the personas
     */
    public Personas getPersonas() {
        return personas;
    }

    /**
     * @param personas the personas to set
     */
    public void setPersonas(Personas personas) {
        this.personas = personas;
    }

    /**
     * @return the estadoEntidades
     */
    public EstadoEntidades getEstadoEntidades() {
        return estadoEntidades;
    }

    /**
     * @param estadoEntidades the estadoEntidades to set
     */
    public void setEstadoEntidades(EstadoEntidades estadoEntidades) {
        this.estadoEntidades = estadoEntidades;
    }

    /**
     * @return the Fechaproceso
     */
    public Date getEntFechaproceso() {
        return Fechaproceso;
    }

    /**
     * @param Fechaproceso the Fechaproceso to set
     */
    public void setEntFechaproceso(Date Fechaproceso) {
        this.Fechaproceso = Fechaproceso;
    }

    /**
     * @return the listAbogados
     */
    public List getListAbogados() {
        return listAbogados;
    }

    /**
     * @param listAbogados the listAbogados to set
     */
    public void setListAbogados(List listAbogados) {
        this.listAbogados = listAbogados;
    }

}
