package CobroCoactivo.Modelo;
// Generated 30/05/2018 02:16:05 PM by Hibernate Tools 4.3.1



import java.math.BigDecimal;
import java.util.Date;

/**
 * EstadoFasesTrabajos generated by hbm2java
 */
public class EstadoFasesTrabajos  implements java.io.Serializable {


     private BigDecimal estfastraId;
     private String estfastraDescripcion;
     private Date estfastraFechainicial;
     private Date estfastraFechafinal;
     private Date estfastraFechaproceso;
     private FasesTrabajos fasesTrabajos;

    public EstadoFasesTrabajos() {
    }

	
    public EstadoFasesTrabajos(BigDecimal estfastraId, String estfastraDescripcion) {
        this.estfastraId = estfastraId;
        this.estfastraDescripcion = estfastraDescripcion;
    }
    public EstadoFasesTrabajos(BigDecimal estfastraId, String estfastraDescripcion, Date estfastraFechainicial, Date estfastraFechafinal, Date estfastraFechaproceso, FasesTrabajos fasesTrabajos) {
       this.estfastraId = estfastraId;
       this.estfastraDescripcion = estfastraDescripcion;
       this.estfastraFechainicial = estfastraFechainicial;
       this.estfastraFechafinal = estfastraFechafinal;
       this.estfastraFechaproceso = estfastraFechaproceso;
       this.fasesTrabajos = fasesTrabajos;
    }
   
    public BigDecimal getEstfastraId() {
        return this.estfastraId;
    }
    
    public void setEstfastraId(BigDecimal estfastraId) {
        this.estfastraId = estfastraId;
    }
    public String getEstfastraDescripcion() {
        return this.estfastraDescripcion;
    }
    
    public void setEstfastraDescripcion(String estfastraDescripcion) {
        this.estfastraDescripcion = estfastraDescripcion;
    }
    public Date getEstfastraFechainicial() {
        return this.estfastraFechainicial;
    }
    
    public void setEstfastraFechainicial(Date estfastraFechainicial) {
        this.estfastraFechainicial = estfastraFechainicial;
    }
    public Date getEstfastraFechafinal() {
        return this.estfastraFechafinal;
    }
    
    public void setEstfastraFechafinal(Date estfastraFechafinal) {
        this.estfastraFechafinal = estfastraFechafinal;
    }
    public Date getEstfastraFechaproceso() {
        return this.estfastraFechaproceso;
    }
    
    public void setEstfastraFechaproceso(Date estfastraFechaproceso) {
        this.estfastraFechaproceso = estfastraFechaproceso;
    }
    public FasesTrabajos getFasesTrabajos() {
        return this.fasesTrabajos;
    }
    
    public void setFasesTrabajos(FasesTrabajos fasesTrabajos) {
        this.fasesTrabajos = fasesTrabajos;
    }




}


