package CobroCoactivo.Modelo;
// Generated 30/05/2018 02:16:05 PM by Hibernate Tools 4.3.1



import java.math.BigDecimal;
import java.util.Date;

/**
 * EstadoDetalleIngresodeu generated by hbm2java
 */
public class EstadoDetalleIngresodeu  implements java.io.Serializable {


     private BigDecimal estdetingdeuId;
     private String estdetingdeuDescripcion;
     private Date estdetingdeuFechainicial;
     private Date estdetingdeuFechafinal;
     private Date estdetingdeuFechaproceso;
     private DetalleIngresoDeudas detalleIngresoDeudas;

    public EstadoDetalleIngresodeu() {
    }

	
    public EstadoDetalleIngresodeu(BigDecimal estdetingdeuId, String estdetingdeuDescripcion) {
        this.estdetingdeuId = estdetingdeuId;
        this.estdetingdeuDescripcion = estdetingdeuDescripcion;
    }
    public EstadoDetalleIngresodeu(BigDecimal estdetingdeuId, String estdetingdeuDescripcion, Date estdetingdeuFechainicial, Date estdetingdeuFechafinal, Date estdetingdeuFechaproceso, DetalleIngresoDeudas detalleIngresoDeudas) {
       this.estdetingdeuId = estdetingdeuId;
       this.estdetingdeuDescripcion = estdetingdeuDescripcion;
       this.estdetingdeuFechainicial = estdetingdeuFechainicial;
       this.estdetingdeuFechafinal = estdetingdeuFechafinal;
       this.estdetingdeuFechaproceso = estdetingdeuFechaproceso;
       this.detalleIngresoDeudas = detalleIngresoDeudas;
    }
   
    public BigDecimal getEstdetingdeuId() {
        return this.estdetingdeuId;
    }
    
    public void setEstdetingdeuId(BigDecimal estdetingdeuId) {
        this.estdetingdeuId = estdetingdeuId;
    }
    public String getEstdetingdeuDescripcion() {
        return this.estdetingdeuDescripcion;
    }
    
    public void setEstdetingdeuDescripcion(String estdetingdeuDescripcion) {
        this.estdetingdeuDescripcion = estdetingdeuDescripcion;
    }
    public Date getEstdetingdeuFechainicial() {
        return this.estdetingdeuFechainicial;
    }
    
    public void setEstdetingdeuFechainicial(Date estdetingdeuFechainicial) {
        this.estdetingdeuFechainicial = estdetingdeuFechainicial;
    }
    public Date getEstdetingdeuFechafinal() {
        return this.estdetingdeuFechafinal;
    }
    
    public void setEstdetingdeuFechafinal(Date estdetingdeuFechafinal) {
        this.estdetingdeuFechafinal = estdetingdeuFechafinal;
    }
    public Date getEstdetingdeuFechaproceso() {
        return this.estdetingdeuFechaproceso;
    }
    
    public void setEstdetingdeuFechaproceso(Date estdetingdeuFechaproceso) {
        this.estdetingdeuFechaproceso = estdetingdeuFechaproceso;
    }
    public DetalleIngresoDeudas getDetalleIngresoDeudas() {
        return this.detalleIngresoDeudas;
    }
    
    public void setDetalleIngresoDeudas(DetalleIngresoDeudas detalleIngresoDeudas) {
        this.detalleIngresoDeudas = detalleIngresoDeudas;
    }




}


