package CobroCoactivo.Modelo;
// Generated 30/05/2018 02:16:05 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.validation.Valid;
import javax.validation.constraints.Digits;
import javax.validation.constraints.Min;
import javax.validation.constraints.Pattern;
import javax.validation.constraints.Size;
import org.hibernate.validator.constraints.NotEmpty;

/**
 * EtapasGenerales generated by hbm2java
 */
public class EtapasGenerales implements java.io.Serializable {

    private BigDecimal etagenId;

    private PlanGenerales planGenerales;
    private EstadoEtapasGenerales estadoEtapasGenerales;
    
    @Size(min = 2, max = 30, message = "Minimo dos caracteres, maximo 30")
    private String etagenDescripcion;
    private Date etagenFechaproceso;
    private String etagenObligatorio;
    
    
   
    @Min(value = 1, message = "Minimo valor 1")
    @Digits(integer = 1, fraction = 0, message = "debe ser un numero")
    private Integer prioridad;
    private Set fasesGeneraleses = new HashSet(0);

    public EtapasGenerales() {
    }

    public EtapasGenerales(PlanGenerales planGenerales, EstadoEtapasGenerales estadoEtapasGenerales, String etagenDescripcion, Date etagenFechaproceso, String etagenObligatorio, Integer prioridad) {
        this.planGenerales = planGenerales;
        this.estadoEtapasGenerales = estadoEtapasGenerales;
        this.etagenDescripcion = etagenDescripcion;
        this.etagenFechaproceso = etagenFechaproceso;
        this.etagenObligatorio = etagenObligatorio;
        this.prioridad = prioridad;
    }
    
    

    public EtapasGenerales(BigDecimal etagenId, PlanGenerales planGenerales, EstadoEtapasGenerales estadoEtapasGenerales, String etagenDescripcion, String etagenObligatorio) {
        this.etagenId = etagenId;
        this.planGenerales = planGenerales;
        this.estadoEtapasGenerales = estadoEtapasGenerales;
        this.etagenDescripcion = etagenDescripcion;
        this.etagenObligatorio = etagenObligatorio;
    }

    public EtapasGenerales(BigDecimal etagenId, PlanGenerales planGenerales, EstadoEtapasGenerales estadoEtapasGenerales, String etagenDescripcion, Date etagenFechaproceso, String etagenObligatorio, Set fasesGeneraleses) {
        this.etagenId = etagenId;
        this.planGenerales = planGenerales;
        this.estadoEtapasGenerales = estadoEtapasGenerales;
        this.etagenDescripcion = etagenDescripcion;
        this.etagenFechaproceso = etagenFechaproceso;
        this.etagenObligatorio = etagenObligatorio;
        this.fasesGeneraleses = fasesGeneraleses;
    }

    public BigDecimal getEtagenId() {
        return this.etagenId;
    }

    public void setEtagenId(BigDecimal etagenId) {
        this.etagenId = etagenId;
    }

    public PlanGenerales getPlanGenerales() {
        return this.planGenerales;
    }

    public void setPlanGenerales(PlanGenerales planGenerales) {
        this.planGenerales = planGenerales;
    }

    public EstadoEtapasGenerales getEstadoEtapasGenerales() {
        return this.estadoEtapasGenerales;
    }

    public void setEstadoEtapasGenerales(EstadoEtapasGenerales estadoEtapasGenerales) {
        this.estadoEtapasGenerales = estadoEtapasGenerales;
    }

    public String getEtagenDescripcion() {
        return this.etagenDescripcion;
    }

    public void setEtagenDescripcion(String etagenDescripcion) {
        this.etagenDescripcion = etagenDescripcion;
    }

    public Date getEtagenFechaproceso() {
        return this.etagenFechaproceso;
    }

    public void setEtagenFechaproceso(Date etagenFechaproceso) {
        this.etagenFechaproceso = etagenFechaproceso;
    }

    public String getEtagenObligatorio() {
        return this.etagenObligatorio;
    }

    public void setEtagenObligatorio(String etagenObligatorio) {
        this.etagenObligatorio = etagenObligatorio;
    }

    public Set getFasesGeneraleses() {
        return this.fasesGeneraleses;
    }

    public void setFasesGeneraleses(Set fasesGeneraleses) {
        this.fasesGeneraleses = fasesGeneraleses;
    }

    /**
     * @return the prioridad
     */
    public Integer getPrioridad() {
        return prioridad;
    }

    /**
     * @param prioridad the prioridad to set
     */
    public void setPrioridad(Integer prioridad) {
        this.prioridad = prioridad;
    }

}
