package CobroCoactivo.Modelo;
// Generated 30/05/2018 02:16:05 PM by Hibernate Tools 4.3.1

import CobroCoactivo.Persistencia.CivDeudas;
import CobroCoactivo.Persistencia.CivEstadoExpedientes;
import CobroCoactivo.Persistencia.CivExpedientes;
import CobroCoactivo.Persistencia.CivTipoExpedientes;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Expedientes generated by hbm2java
 */
public class Expedientes implements java.io.Serializable {

    private int Id;
    private TipoExpedientes tipoExpedientes;
    private EstadoExpedientes estadoExpedientes;
    private Deudas deudas;
    private String Referencia;
    private Date Fechaproceso;
    private String Ubicacion;
    private Set detalleExpedienteses = new HashSet(0);

    public Expedientes() {
    }

    public Expedientes(CivExpedientes civExpedientes) {
        this.Id = civExpedientes.getExpId().intValue();
        this.Referencia = civExpedientes.getExpReferencia();
        this.Fechaproceso = civExpedientes.getExpFechaproceso();
        this.Ubicacion = civExpedientes.getExpUbicacion();
    }

    public Expedientes(CivExpedientes civExpedientes, CivTipoExpedientes civTipoExpedientes) {
        this.Id = civExpedientes.getExpId().intValue();
        this.Referencia = civExpedientes.getExpReferencia();
        this.Fechaproceso = civExpedientes.getExpFechaproceso();
        this.Ubicacion = civExpedientes.getExpUbicacion();
        this.tipoExpedientes = new TipoExpedientes(civTipoExpedientes);
    }

    public Expedientes(CivExpedientes civExpedientes, CivTipoExpedientes civTipoExpedientes, CivEstadoExpedientes civEstadoExpedientes) {
        this.Id = civExpedientes.getExpId().intValue();
        this.Referencia = civExpedientes.getExpReferencia();
        this.Fechaproceso = civExpedientes.getExpFechaproceso();
        this.Ubicacion = civExpedientes.getExpUbicacion();
        this.tipoExpedientes = new TipoExpedientes(civTipoExpedientes);
        this.estadoExpedientes = new EstadoExpedientes(civEstadoExpedientes);
    }

    public Expedientes(CivExpedientes civExpedientes, CivTipoExpedientes civTipoExpedientes, CivEstadoExpedientes civEstadoExpedientes, CivDeudas civDeudas) {
        this.Id = civExpedientes.getExpId().intValue();
        this.Referencia = civExpedientes.getExpReferencia();
        this.Fechaproceso = civExpedientes.getExpFechaproceso();
        this.Ubicacion = civExpedientes.getExpUbicacion();
        this.tipoExpedientes = new TipoExpedientes(civTipoExpedientes);
        this.estadoExpedientes = new EstadoExpedientes(civEstadoExpedientes);
        this.deudas = new Deudas(civDeudas);
    }

    public TipoExpedientes getTipoExpedientes() {
        return this.tipoExpedientes;
    }

    public void setTipoExpedientes(TipoExpedientes tipoExpedientes) {
        this.tipoExpedientes = tipoExpedientes;
    }

    public EstadoExpedientes getEstadoExpedientes() {
        return this.estadoExpedientes;
    }

    public void setEstadoExpedientes(EstadoExpedientes estadoExpedientes) {
        this.estadoExpedientes = estadoExpedientes;
    }

    public Deudas getDeudas() {
        return this.deudas;
    }

    public void setDeudas(Deudas deudas) {
        this.deudas = deudas;
    }

    public Set getDetalleExpedienteses() {
        return this.detalleExpedienteses;
    }

    public void setDetalleExpedienteses(Set detalleExpedienteses) {
        this.detalleExpedienteses = detalleExpedienteses;
    }

    /**
     * @return the Ubicacion
     */
    public String getUbicacion() {
        return Ubicacion;
    }

    /**
     * @param Ubicacion the Ubicacion to set
     */
    public void setUbicacion(String Ubicacion) {
        this.Ubicacion = Ubicacion;
    }

    /**
     * @return the Id
     */
    public int getId() {
        return Id;
    }

    /**
     * @param Id the Id to set
     */
    public void setId(int Id) {
        this.Id = Id;
    }

    /**
     * @return the Referencia
     */
    public String getReferencia() {
        return Referencia;
    }

    /**
     * @param Referencia the Refencia to set
     */
    public void setReferencia(String Referencia) {
        this.Referencia = Referencia;
    }

    /**
     * @return the Fechaproceso
     */
    public Date getFechaproceso() {
        return Fechaproceso;
    }

    /**
     * @param Fechaproceso the Fechaproceso to set
     */
    public void setFechaproceso(Date Fechaproceso) {
        this.Fechaproceso = Fechaproceso;
    }

}
