package CobroCoactivo.Modelo;
// Generated 30/05/2018 02:16:05 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;
import javax.validation.constraints.Digits;
import javax.validation.constraints.Min;
import javax.validation.constraints.Size;

/**
 * FasesGenerales generated by hbm2java
 */
public class FasesGenerales implements java.io.Serializable {

    private BigDecimal fasgenId;
    private EtapasGenerales etapasGenerales;
    private EstadoFasesGenerales estadoFasesGenerales;
    private DocumenGenerales documenGenerales;
    @Size(min = 2, max = 30, message = "Minimo 2 caracteres, Maximo 30")
    private String fasgenDescripcion;
    private Date fasgenFechaproceso;

    @Min(value = 1, message = "Minimo valor 1")
    @Digits(integer = 2, fraction = 0, message = "debe ser un numero menor a 100")
    private Integer fasgenDianim;
    @Min(value = 1, message = "Minimo valor 1")
    @Digits(integer = 2, fraction = 0, message = "debe ser un numero menor a 100")  
    private Integer fasgenDiamax;
    private String fasgenObligatorio;

    public FasesGenerales() {
    }

    public FasesGenerales(EtapasGenerales etapasGenerales, EstadoFasesGenerales estadoFasesGenerales, DocumenGenerales documenGenerales, String fasgenDescripcion, Date fasgenFechaproceso, Integer fasgenDianim, Integer fasgenDiamax, String fasgenObligatorio) {
        this.etapasGenerales = etapasGenerales;
        this.estadoFasesGenerales = estadoFasesGenerales;
        this.documenGenerales = documenGenerales;
        this.fasgenDescripcion = fasgenDescripcion;
        this.fasgenFechaproceso = fasgenFechaproceso;
        this.fasgenDianim = fasgenDianim;
        this.fasgenDiamax = fasgenDiamax;
        this.fasgenObligatorio = fasgenObligatorio;
    }

    public FasesGenerales(BigDecimal fasgenId, EtapasGenerales etapasGenerales, EstadoFasesGenerales estadoFasesGenerales, DocumenGenerales documenGenerales, String fasgenDescripcion, String fasgenObligatorio) {
        this.fasgenId = fasgenId;
        this.etapasGenerales = etapasGenerales;
        this.estadoFasesGenerales = estadoFasesGenerales;
        this.documenGenerales = documenGenerales;
        this.fasgenDescripcion = fasgenDescripcion;
        this.fasgenObligatorio = fasgenObligatorio;
    }

    public FasesGenerales(BigDecimal fasgenId, EtapasGenerales etapasGenerales, EstadoFasesGenerales estadoFasesGenerales, DocumenGenerales documenGenerales, String fasgenDescripcion, Date fasgenFechaproceso, Integer fasgenDianim, Integer fasgenDiamax, String fasgenObligatorio) {
        this.fasgenId = fasgenId;
        this.etapasGenerales = etapasGenerales;
        this.estadoFasesGenerales = estadoFasesGenerales;
        this.documenGenerales = documenGenerales;
        this.fasgenDescripcion = fasgenDescripcion;
        this.fasgenFechaproceso = fasgenFechaproceso;
        this.fasgenDianim = fasgenDianim;
        this.fasgenDiamax = fasgenDiamax;
        this.fasgenObligatorio = fasgenObligatorio;
    }

    public BigDecimal getFasgenId() {
        return this.fasgenId;
    }

    public void setFasgenId(BigDecimal fasgenId) {
        this.fasgenId = fasgenId;
    }

    public EtapasGenerales getEtapasGenerales() {
        return this.etapasGenerales;
    }

    public void setEtapasGenerales(EtapasGenerales etapasGenerales) {
        this.etapasGenerales = etapasGenerales;
    }

    public EstadoFasesGenerales getEstadoFasesGenerales() {
        return this.estadoFasesGenerales;
    }

    public void setEstadoFasesGenerales(EstadoFasesGenerales estadoFasesGenerales) {
        this.estadoFasesGenerales = estadoFasesGenerales;
    }

    public DocumenGenerales getDocumenGenerales() {
        return this.documenGenerales;
    }

    public void setDocumenGenerales(DocumenGenerales documenGenerales) {
        this.documenGenerales = documenGenerales;
    }

    public String getFasgenDescripcion() {
        return this.fasgenDescripcion;
    }

    public void setFasgenDescripcion(String fasgenDescripcion) {
        this.fasgenDescripcion = fasgenDescripcion;
    }

    public Date getFasgenFechaproceso() {
        return this.fasgenFechaproceso;
    }

    public void setFasgenFechaproceso(Date fasgenFechaproceso) {
        this.fasgenFechaproceso = fasgenFechaproceso;
    }

    public Integer getFasgenDianim() {
        return this.fasgenDianim;
    }

    public void setFasgenDianim(Integer fasgenDianim) {
        this.fasgenDianim = fasgenDianim;
    }

    public Integer getFasgenDiamax() {
        return this.fasgenDiamax;
    }

    public void setFasgenDiamax(Integer fasgenDiamax) {
        this.fasgenDiamax = fasgenDiamax;
    }

    public String getFasgenObligatorio() {
        return this.fasgenObligatorio;
    }

    public void setFasgenObligatorio(String fasgenObligatorio) {
        this.fasgenObligatorio = fasgenObligatorio;
    }

}
