package CobroCoactivo.Modelo;
// Generated 30/05/2018 02:16:05 PM by Hibernate Tools 4.3.1

import CobroCoactivo.Persistencia.CivDocumenGenerales;
import CobroCoactivo.Persistencia.CivEstadoDeudas;
import CobroCoactivo.Persistencia.CivEstadoFasesGenerales;
import CobroCoactivo.Persistencia.CivEtapasGenerales;
import CobroCoactivo.Persistencia.CivFasesGenerales;
import java.math.BigDecimal;
import java.util.Date;
import javax.validation.constraints.Digits;
import javax.validation.constraints.Min;
import javax.validation.constraints.Size;

/**
 * FasesGenerales generated by hbm2java
 */
public class FasesGenerales implements java.io.Serializable {

    private int Id;
    private EtapasGenerales etapasGenerales;
    private EstadoFasesGenerales estadoFasesGenerales;
    private DocumenGenerales documenGenerales;
    @Size(min = 2, max = 30, message = "Minimo 2 caracteres, Maximo 30")
    private String Descripcion;
    private Date Fechaproceso;

    @Min(value = 1, message = "Minimo valor 1")
    @Digits(integer = 2, fraction = 0, message = "debe ser un numero menor a 100")
    private Integer Dianim;
    @Min(value = 1, message = "Minimo valor 1")
    @Digits(integer = 2, fraction = 0, message = "debe ser un numero menor a 100")  
    private Integer Diamax;
    private String Obligatorio;

    public FasesGenerales() {
    }

    public FasesGenerales(CivFasesGenerales civFasesGenerales) {
        this.Id = civFasesGenerales.getFasgenId().intValue();
        this.Descripcion = civFasesGenerales.getFasgenDescripcion();
        this.Fechaproceso = civFasesGenerales.getFasgenFechaproceso();
        this.Dianim = civFasesGenerales.getFasgenDianim().intValue();
        this.Diamax = civFasesGenerales.getFasgenDiamax().intValue();
    }
    public FasesGenerales(CivFasesGenerales civFasesGenerales,CivEstadoFasesGenerales civEstadoFasesGenerales) {
        this.Id = civFasesGenerales.getFasgenId().intValue();
        this.Descripcion = civFasesGenerales.getFasgenDescripcion();
        this.Fechaproceso = civFasesGenerales.getFasgenFechaproceso();
        this.Dianim = civFasesGenerales.getFasgenDianim().intValue();
        this.Diamax = civFasesGenerales.getFasgenDiamax().intValue();
        this.estadoFasesGenerales = new EstadoFasesGenerales(civEstadoFasesGenerales);
    }
    public FasesGenerales(CivFasesGenerales civFasesGenerales,CivEstadoFasesGenerales civEstadoFasesGenerales,CivEtapasGenerales civEtapasGenerales,CivDocumenGenerales civDocumenGenerales) {
        this.Id = civFasesGenerales.getFasgenId().intValue();
        this.Descripcion = civFasesGenerales.getFasgenDescripcion();
        this.Fechaproceso = civFasesGenerales.getFasgenFechaproceso();
        this.Dianim = civFasesGenerales.getFasgenDianim().intValue();
        this.Diamax = civFasesGenerales.getFasgenDiamax().intValue();
        this.estadoFasesGenerales = new EstadoFasesGenerales(civEstadoFasesGenerales);
        this.etapasGenerales = new EtapasGenerales(civEtapasGenerales);
        this.documenGenerales = new DocumenGenerales(civDocumenGenerales,civDocumenGenerales.getCivEstadoDocumengenerales());
    }

  

    /**
     * @return the Id
     */
    public int getId() {
        return Id;
    }

    /**
     * @param Id the Id to set
     */
    public void setId(int Id) {
        this.Id = Id;
    }

    /**
     * @return the etapasGenerales
     */
    public EtapasGenerales getEtapasGenerales() {
        return etapasGenerales;
    }

    /**
     * @param etapasGenerales the etapasGenerales to set
     */
    public void setEtapasGenerales(EtapasGenerales etapasGenerales) {
        this.etapasGenerales = etapasGenerales;
    }

    /**
     * @return the estadoFasesGenerales
     */
    public EstadoFasesGenerales getEstadoFasesGenerales() {
        return estadoFasesGenerales;
    }

    /**
     * @param estadoFasesGenerales the estadoFasesGenerales to set
     */
    public void setEstadoFasesGenerales(EstadoFasesGenerales estadoFasesGenerales) {
        this.estadoFasesGenerales = estadoFasesGenerales;
    }

    /**
     * @return the documenGenerales
     */
    public DocumenGenerales getDocumenGenerales() {
        return documenGenerales;
    }

    /**
     * @param documenGenerales the documenGenerales to set
     */
    public void setDocumenGenerales(DocumenGenerales documenGenerales) {
        this.documenGenerales = documenGenerales;
    }

    /**
     * @return the Descripcion
     */
    public String getDescripcion() {
        return Descripcion;
    }

    /**
     * @param Descripcion the Descripcion to set
     */
    public void setDescripcion(String Descripcion) {
        this.Descripcion = Descripcion;
    }

    /**
     * @return the Fechaproceso
     */
    public Date getFechaproceso() {
        return Fechaproceso;
    }

    /**
     * @param Fechaproceso the Fechaproceso to set
     */
    public void setFechaproceso(Date Fechaproceso) {
        this.Fechaproceso = Fechaproceso;
    }

    /**
     * @return the Dianim
     */
    public Integer getDianim() {
        return Dianim;
    }

    /**
     * @param Dianim the Dianim to set
     */
    public void setDianim(Integer Dianim) {
        this.Dianim = Dianim;
    }

    /**
     * @return the Diamax
     */
    public Integer getDiamax() {
        return Diamax;
    }

    /**
     * @param Diamax the Diamax to set
     */
    public void setDiamax(Integer Diamax) {
        this.Diamax = Diamax;
    }

    /**
     * @return the Obligatorio
     */
    public String getObligatorio() {
        return Obligatorio;
    }

    /**
     * @param Obligatorio the Obligatorio to set
     */
    public void setObligatorio(String Obligatorio) {
        this.Obligatorio = Obligatorio;
    }

}
