package CobroCoactivo.Modelo;
// Generated 30/05/2018 02:16:05 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * FasesTrabajos generated by hbm2java
 */
public class FasesTrabajos  implements java.io.Serializable {


     private BigDecimal fastraId;
     private ReporteTrabajos reporteTrabajos;
     private EtapasTrabajos etapasTrabajos;
     private EstadoFasesTrabajos estadoFasesTrabajos;
     private String fastraDescripcion;
     private BigDecimal fastraEstfastraFk;
     private Date fastraFechaproceso;
     private BigDecimal fastraDianim;
     private BigDecimal fastraDiamax;

    public FasesTrabajos() {
    }

	
    public FasesTrabajos(EtapasTrabajos etapasTrabajos, EstadoFasesTrabajos estadoFasesTrabajos, String fastraDescripcion, BigDecimal fastraEstfastraFk) {
        this.etapasTrabajos = etapasTrabajos;
        this.estadoFasesTrabajos = estadoFasesTrabajos;
        this.fastraDescripcion = fastraDescripcion;
        this.fastraEstfastraFk = fastraEstfastraFk;
    }
    public FasesTrabajos(ReporteTrabajos reporteTrabajos, EtapasTrabajos etapasTrabajos, EstadoFasesTrabajos estadoFasesTrabajos, String fastraDescripcion, BigDecimal fastraEstfastraFk, Date fastraFechaproceso, BigDecimal fastraDianim, BigDecimal fastraDiamax) {
       this.reporteTrabajos = reporteTrabajos;
       this.etapasTrabajos = etapasTrabajos;
       this.estadoFasesTrabajos = estadoFasesTrabajos;
       this.fastraDescripcion = fastraDescripcion;
       this.fastraEstfastraFk = fastraEstfastraFk;
       this.fastraFechaproceso = fastraFechaproceso;
       this.fastraDianim = fastraDianim;
       this.fastraDiamax = fastraDiamax;
    }
   
    public BigDecimal getFastraId() {
        return this.fastraId;
    }
    
    public void setFastraId(BigDecimal fastraId) {
        this.fastraId = fastraId;
    }
    public ReporteTrabajos getReporteTrabajos() {
        return this.reporteTrabajos;
    }
    
    public void setReporteTrabajos(ReporteTrabajos reporteTrabajos) {
        this.reporteTrabajos = reporteTrabajos;
    }
    public EtapasTrabajos getEtapasTrabajos() {
        return this.etapasTrabajos;
    }
    
    public void setEtapasTrabajos(EtapasTrabajos etapasTrabajos) {
        this.etapasTrabajos = etapasTrabajos;
    }
    public EstadoFasesTrabajos getEstadoFasesTrabajos() {
        return this.estadoFasesTrabajos;
    }
    
    public void setEstadoFasesTrabajos(EstadoFasesTrabajos estadoFasesTrabajos) {
        this.estadoFasesTrabajos = estadoFasesTrabajos;
    }
    public String getFastraDescripcion() {
        return this.fastraDescripcion;
    }
    
    public void setFastraDescripcion(String fastraDescripcion) {
        this.fastraDescripcion = fastraDescripcion;
    }
    public BigDecimal getFastraEstfastraFk() {
        return this.fastraEstfastraFk;
    }
    
    public void setFastraEstfastraFk(BigDecimal fastraEstfastraFk) {
        this.fastraEstfastraFk = fastraEstfastraFk;
    }
    public Date getFastraFechaproceso() {
        return this.fastraFechaproceso;
    }
    
    public void setFastraFechaproceso(Date fastraFechaproceso) {
        this.fastraFechaproceso = fastraFechaproceso;
    }
    public BigDecimal getFastraDianim() {
        return this.fastraDianim;
    }
    
    public void setFastraDianim(BigDecimal fastraDianim) {
        this.fastraDianim = fastraDianim;
    }
    public BigDecimal getFastraDiamax() {
        return this.fastraDiamax;
    }
    
    public void setFastraDiamax(BigDecimal fastraDiamax) {
        this.fastraDiamax = fastraDiamax;
    }




}


