package CobroCoactivo.Modelo;
// Generated 30/05/2018 02:16:05 PM by Hibernate Tools 4.3.1

import CobroCoactivo.Persistencia.CivDocumenGenerales;
import CobroCoactivo.Persistencia.CivEstadoFasesGenerales;
import CobroCoactivo.Persistencia.CivEtapasGenerales;
import CobroCoactivo.Persistencia.CivFasesGenerales;
import java.util.Date;
import javax.validation.constraints.Digits;
import javax.validation.constraints.Min;
import javax.validation.constraints.Size;

/**
 * FasesGenerales generated by hbm2java
 */
public class FasesGenerales implements java.io.Serializable {

    private int Id;
    private EtapasGenerales etapasGenerales;
    private EstadoFasesGenerales estadoFasesGenerales;
    private DocumenGenerales documenGenerales;
    @Size(min = 2, max = 30, message = "Minimo 2 caracteres, Maximo 30")
    private String descripcion;
    private Date fechaproceso;

    @Min(value = 1, message = "Minimo valor 1")
    @Digits(integer = 2, fraction = 0, message = "debe ser un numero menor a 100")
    private Integer dianim;
    @Min(value = 1, message = "Minimo valor 1")
    @Digits(integer = 2, fraction = 0, message = "debe ser un numero menor a 100")  
    private Integer diamax;
    private String obligatorio;

    public FasesGenerales() {
    }

    public FasesGenerales(CivFasesGenerales civFasesGenerales) {
        this.Id = civFasesGenerales.getFasgenId().intValue();
        this.descripcion = civFasesGenerales.getFasgenDescripcion();
        this.fechaproceso = civFasesGenerales.getFasgenFechaproceso();
        this.dianim = civFasesGenerales.getFasgenDianim().intValue();
        this.diamax = civFasesGenerales.getFasgenDiamax().intValue();
    }
    public FasesGenerales(CivFasesGenerales civFasesGenerales,CivEstadoFasesGenerales civEstadoFasesGenerales) {
        this.Id = civFasesGenerales.getFasgenId().intValue();
        this.descripcion = civFasesGenerales.getFasgenDescripcion();
        this.fechaproceso = civFasesGenerales.getFasgenFechaproceso();
        this.dianim = civFasesGenerales.getFasgenDianim().intValue();
        this.diamax = civFasesGenerales.getFasgenDiamax().intValue();
        this.estadoFasesGenerales = new EstadoFasesGenerales(civEstadoFasesGenerales);
    }
    public FasesGenerales(CivFasesGenerales civFasesGenerales,CivEstadoFasesGenerales civEstadoFasesGenerales,CivEtapasGenerales civEtapasGenerales,CivDocumenGenerales civDocumenGenerales) {
        this.Id = civFasesGenerales.getFasgenId().intValue();
        this.descripcion = civFasesGenerales.getFasgenDescripcion();
        this.fechaproceso = civFasesGenerales.getFasgenFechaproceso();
        this.dianim = civFasesGenerales.getFasgenDianim().intValue();
        this.diamax = civFasesGenerales.getFasgenDiamax().intValue();
        this.obligatorio = civFasesGenerales.getFasgenObligatorio();
        this.estadoFasesGenerales = new EstadoFasesGenerales(civEstadoFasesGenerales);
        this.etapasGenerales = new EtapasGenerales(civEtapasGenerales);
        this.documenGenerales = new DocumenGenerales(civDocumenGenerales,civDocumenGenerales.getCivEstadoDocumengenerales());
    }

  

    /**
     * @return the Id
     */
    public int getId() {
        return Id;
    }

    /**
     * @param Id the Id to set
     */
    public void setId(int Id) {
        this.Id = Id;
    }

    /**
     * @return the etapasGenerales
     */
    public EtapasGenerales getEtapasGenerales() {
        return etapasGenerales;
    }

    /**
     * @param etapasGenerales the etapasGenerales to set
     */
    public void setEtapasGenerales(EtapasGenerales etapasGenerales) {
        this.etapasGenerales = etapasGenerales;
    }

    /**
     * @return the estadoFasesGenerales
     */
    public EstadoFasesGenerales getEstadoFasesGenerales() {
        return estadoFasesGenerales;
    }

    /**
     * @param estadoFasesGenerales the estadoFasesGenerales to set
     */
    public void setEstadoFasesGenerales(EstadoFasesGenerales estadoFasesGenerales) {
        this.estadoFasesGenerales = estadoFasesGenerales;
    }

    /**
     * @return the documenGenerales
     */
    public DocumenGenerales getDocumenGenerales() {
        return documenGenerales;
    }

    /**
     * @param documenGenerales the documenGenerales to set
     */
    public void setDocumenGenerales(DocumenGenerales documenGenerales) {
        this.documenGenerales = documenGenerales;
    }

    /**
     * @return the Descripcion
     */
    public String getDescripcion() {
        return descripcion;
    }

    /**
     * @param Descripcion the Descripcion to set
     */
    public void setDescripcion(String Descripcion) {
        this.descripcion = Descripcion;
    }

    /**
     * @return the Fechaproceso
     */
    public Date getFechaproceso() {
        return fechaproceso;
    }

    /**
     * @param Fechaproceso the Fechaproceso to set
     */
    public void setFechaproceso(Date Fechaproceso) {
        this.fechaproceso = Fechaproceso;
    }

    /**
     * @return the Dianim
     */
    public Integer getDianim() {
        return dianim;
    }

    /**
     * @param Dianim the Dianim to set
     */
    public void setDianim(Integer Dianim) {
        this.dianim = Dianim;
    }

    /**
     * @return the Diamax
     */
    public Integer getDiamax() {
        return diamax;
    }

    /**
     * @param Diamax the Diamax to set
     */
    public void setDiamax(Integer Diamax) {
        this.diamax = Diamax;
    }

    /**
     * @return the Obligatorio
     */
    public String getObligatorio() {
        return obligatorio;
    }

    /**
     * @param Obligatorio the Obligatorio to set
     */
    public void setObligatorio(String Obligatorio) {
        this.obligatorio = Obligatorio;
    }

}
