package CobroCoactivo.Modelo;
// Generated 30/05/2018 02:16:05 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * IngresoDeudas generated by hbm2java
 */
public class IngresoDeudas  implements java.io.Serializable {


     private BigDecimal ingdeuId;
     private TipoIngresoDeudas tipoIngresoDeudas;
     private EstadoIngresoDeudas estadoIngresoDeudas;
     private String ingdeuReferencia;
     private Date ingdeuFechaproceso;
     private Set detalleIngresoDeudases = new HashSet(0);

    public IngresoDeudas() {
    }

	
    public IngresoDeudas(BigDecimal ingdeuId, TipoIngresoDeudas tipoIngresoDeudas, EstadoIngresoDeudas estadoIngresoDeudas) {
        this.ingdeuId = ingdeuId;
        this.tipoIngresoDeudas = tipoIngresoDeudas;
        this.estadoIngresoDeudas = estadoIngresoDeudas;
    }
    public IngresoDeudas(BigDecimal ingdeuId, TipoIngresoDeudas tipoIngresoDeudas, EstadoIngresoDeudas estadoIngresoDeudas, String ingdeuReferencia, Date ingdeuFechaproceso, Set detalleIngresoDeudases) {
       this.ingdeuId = ingdeuId;
       this.tipoIngresoDeudas = tipoIngresoDeudas;
       this.estadoIngresoDeudas = estadoIngresoDeudas;
       this.ingdeuReferencia = ingdeuReferencia;
       this.ingdeuFechaproceso = ingdeuFechaproceso;
       this.detalleIngresoDeudases = detalleIngresoDeudases;
    }
   
    public BigDecimal getIngdeuId() {
        return this.ingdeuId;
    }
    
    public void setIngdeuId(BigDecimal ingdeuId) {
        this.ingdeuId = ingdeuId;
    }
    public TipoIngresoDeudas getTipoIngresoDeudas() {
        return this.tipoIngresoDeudas;
    }
    
    public void setTipoIngresoDeudas(TipoIngresoDeudas tipoIngresoDeudas) {
        this.tipoIngresoDeudas = tipoIngresoDeudas;
    }
    public EstadoIngresoDeudas getEstadoIngresoDeudas() {
        return this.estadoIngresoDeudas;
    }
    
    public void setEstadoIngresoDeudas(EstadoIngresoDeudas estadoIngresoDeudas) {
        this.estadoIngresoDeudas = estadoIngresoDeudas;
    }
    public String getIngdeuReferencia() {
        return this.ingdeuReferencia;
    }
    
    public void setIngdeuReferencia(String ingdeuReferencia) {
        this.ingdeuReferencia = ingdeuReferencia;
    }
    public Date getIngdeuFechaproceso() {
        return this.ingdeuFechaproceso;
    }
    
    public void setIngdeuFechaproceso(Date ingdeuFechaproceso) {
        this.ingdeuFechaproceso = ingdeuFechaproceso;
    }
    public Set getDetalleIngresoDeudases() {
        return this.detalleIngresoDeudases;
    }
    
    public void setDetalleIngresoDeudases(Set detalleIngresoDeudases) {
        this.detalleIngresoDeudases = detalleIngresoDeudases;
    }




}


