package CobroCoactivo.Modelo;
// Generated 30/05/2018 02:16:05 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Perfiles generated by hbm2java
 */
public class Perfiles  implements java.io.Serializable {


     private BigDecimal perfId;
     private EstadoPerfiles estadoPerfiles;
     private String perfNombre;
     private Date perfFechaproceso;
     private Set recursoses = new HashSet(0);

    public Perfiles() {
    }

	
    public Perfiles(BigDecimal perfId, EstadoPerfiles estadoPerfiles, String perfNombre) {
        this.perfId = perfId;
        this.estadoPerfiles = estadoPerfiles;
        this.perfNombre = perfNombre;
    }
    public Perfiles(BigDecimal perfId, EstadoPerfiles estadoPerfiles, String perfNombre, Date perfFechaproceso, Set recursoses) {
       this.perfId = perfId;
       this.estadoPerfiles = estadoPerfiles;
       this.perfNombre = perfNombre;
       this.perfFechaproceso = perfFechaproceso;
       this.recursoses = recursoses;
    }
   
    public BigDecimal getPerfId() {
        return this.perfId;
    }
    
    public void setPerfId(BigDecimal perfId) {
        this.perfId = perfId;
    }
    public EstadoPerfiles getEstadoPerfiles() {
        return this.estadoPerfiles;
    }
    
    public void setEstadoPerfiles(EstadoPerfiles estadoPerfiles) {
        this.estadoPerfiles = estadoPerfiles;
    }
    public String getPerfNombre() {
        return this.perfNombre;
    }
    
    public void setPerfNombre(String perfNombre) {
        this.perfNombre = perfNombre;
    }
    public Date getPerfFechaproceso() {
        return this.perfFechaproceso;
    }
    
    public void setPerfFechaproceso(Date perfFechaproceso) {
        this.perfFechaproceso = perfFechaproceso;
    }
    public Set getRecursoses() {
        return this.recursoses;
    }
    
    public void setRecursoses(Set recursoses) {
        this.recursoses = recursoses;
    }




}


