package CobroCoactivo.Modelo;
// Generated 30/05/2018 02:16:05 PM by Hibernate Tools 4.3.1

import CobroCoactivo.Persistencia.CivEstadoPlanTrabajos;
import CobroCoactivo.Persistencia.CivPlanTrabajos;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

/**
 * PlanTrabajos generated by hbm2java
 */
public class PlanTrabajos implements java.io.Serializable {

    private int Id;
    private EstadoPlanTrabajos estadoPlanTrabajos;
    private String Descripcion;
    private Date Fechaproceso;
    private List<EtapasTrabajos> listaEtapasTrabajo = new ArrayList<>();
    private int countDeudas = 0;
    

    public PlanTrabajos() {
    }

    public PlanTrabajos(CivPlanTrabajos civPlanTrabajos, CivEstadoPlanTrabajos civEstadoPlanTrabajos) {
        this.Id = civPlanTrabajos.getPlatraId().intValue();
        this.estadoPlanTrabajos = new EstadoPlanTrabajos(civEstadoPlanTrabajos);
        this.Descripcion = civPlanTrabajos.getPlatraDescripcion();
        this.Fechaproceso = civPlanTrabajos.getPlatraFechaproceso();
    }

    /**
     * @return the Id
     */
    public int getId() {
        return Id;
    }

    /**
     * @param Id the Id to set
     */
    public void setId(int Id) {
        this.Id = Id;
    }

    /**
     * @return the estadoPlanTrabajos
     */
    public EstadoPlanTrabajos getEstadoPlanTrabajos() {
        return estadoPlanTrabajos;
    }

    /**
     * @param estadoPlanTrabajos the estadoPlanTrabajos to set
     */
    public void setEstadoPlanTrabajos(EstadoPlanTrabajos estadoPlanTrabajos) {
        this.estadoPlanTrabajos = estadoPlanTrabajos;
    }

    /**
     * @return the Descripcion
     */
    public String getDescripcion() {
        return Descripcion;
    }

    /**
     * @param Descripcion the Descripcion to set
     */
    public void setDescripcion(String Descripcion) {
        this.Descripcion = Descripcion;
    }

    /**
     * @return the Fechaproceso
     */
    public Date getFechaproceso() {
        return Fechaproceso;
    }

    /**
     * @param Fechaproceso the Fechaproceso to set
     */
    public void setFechaproceso(Date Fechaproceso) {
        this.Fechaproceso = Fechaproceso;
    }

    /**
     * @return the listaEtapasTrabajo
     */
    public List<EtapasTrabajos> getListaEtapasTrabajo() {
        return listaEtapasTrabajo;
    }

    /**
     * @param listaEtapasTrabajo the listaEtapasTrabajo to set
     */
    public void setListaEtapasTrabajo(List<EtapasTrabajos> listaEtapasTrabajo) {
        this.listaEtapasTrabajo = listaEtapasTrabajo;
    }

    /**
     * @return the countDeudas
     */
    public int getCountDeudas() {
        return countDeudas;
    }

    /**
     * @param countDeudas the countDeudas to set
     */
    public void setCountDeudas(int countDeudas) {
        this.countDeudas = countDeudas;
    }


}
