package CobroCoactivo.Modelo;
// Generated 30/05/2018 02:16:05 PM by Hibernate Tools 4.3.1

import CobroCoactivo.Persistencia.CivEstadoPlanGenerales;
import CobroCoactivo.Persistencia.CivPlanGenerales;
import java.util.Date;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

/**
 * PlanGenerales generated by hbm2java
 */
public class PlanGenerales implements java.io.Serializable {

    private int Id;
    private EstadoPlanGenerales estadoPlanGenerales = new EstadoPlanGenerales();

    @NotNull(message = "El nombre del Plan no puede ser nulo")
    private String Descripcion;

    private Date Fechaproceso;

    public PlanGenerales() {
    }

    public PlanGenerales(CivPlanGenerales civPlanGenerales) {
        this.Id = civPlanGenerales.getPlagenId().intValue();
        this.Descripcion = civPlanGenerales.getPlagenDescripcion();
        this.Fechaproceso = civPlanGenerales.getPlagenFechaproceso();
    }

    public PlanGenerales(CivPlanGenerales civPlanGenerales, CivEstadoPlanGenerales civEstadoPlanGenerales) {
        this.Id = civPlanGenerales.getPlagenId().intValue();
        this.Descripcion = civPlanGenerales.getPlagenDescripcion();
        this.Fechaproceso = civPlanGenerales.getPlagenFechaproceso();
        this.estadoPlanGenerales = new EstadoPlanGenerales(civEstadoPlanGenerales);
    }

    /**
     * @return the Id
     */
    public int getId() {
        return Id;
    }

    /**
     * @param Id the Id to set
     */
    public void setId(int Id) {
        this.Id = Id;
    }

    /**
     * @return the estadoPlanGenerales
     */
    public EstadoPlanGenerales getEstadoPlanGenerales() {
        return estadoPlanGenerales;
    }

    /**
     * @param estadoPlanGenerales the estadoPlanGenerales to set
     */
    public void setEstadoPlanGenerales(EstadoPlanGenerales estadoPlanGenerales) {
        this.estadoPlanGenerales = estadoPlanGenerales;
    }

    /**
     * @return the Descripcion
     */
    public String getDescripcion() {
        return Descripcion;
    }

    /**
     * @param Descripcion the Descripcion to set
     */
    public void setDescripcion(String Descripcion) {
        this.Descripcion = Descripcion;
    }

    /**
     * @return the Fechaproceso
     */
    public Date getFechaproceso() {
        return Fechaproceso;
    }

    /**
     * @param Fechaproceso the Fechaproceso to set
     */
    public void setFechaproceso(Date Fechaproceso) {
        this.Fechaproceso = Fechaproceso;
    }

}
