package CobroCoactivo.Modelo;
// Generated 30/05/2018 02:16:05 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * PlanTrabajos generated by hbm2java
 */
public class PlanTrabajos  implements java.io.Serializable {


     private BigDecimal platraId;
     private EstadoPlanTrabajos estadoPlanTrabajos;
     private String platraDescripcion;
     private Date platraFechaproceso;
     private Set etapasTrabajoses = new HashSet(0);

    public PlanTrabajos() {
    }

	
    public PlanTrabajos(BigDecimal platraId, EstadoPlanTrabajos estadoPlanTrabajos, String platraDescripcion) {
        this.platraId = platraId;
        this.estadoPlanTrabajos = estadoPlanTrabajos;
        this.platraDescripcion = platraDescripcion;
    }
    public PlanTrabajos(BigDecimal platraId, EstadoPlanTrabajos estadoPlanTrabajos, String platraDescripcion, Date platraFechaproceso, Set etapasTrabajoses) {
       this.platraId = platraId;
       this.estadoPlanTrabajos = estadoPlanTrabajos;
       this.platraDescripcion = platraDescripcion;
       this.platraFechaproceso = platraFechaproceso;
       this.etapasTrabajoses = etapasTrabajoses;
    }
   
    public BigDecimal getPlatraId() {
        return this.platraId;
    }
    
    public void setPlatraId(BigDecimal platraId) {
        this.platraId = platraId;
    }
    public EstadoPlanTrabajos getEstadoPlanTrabajos() {
        return this.estadoPlanTrabajos;
    }
    
    public void setEstadoPlanTrabajos(EstadoPlanTrabajos estadoPlanTrabajos) {
        this.estadoPlanTrabajos = estadoPlanTrabajos;
    }
    public String getPlatraDescripcion() {
        return this.platraDescripcion;
    }
    
    public void setPlatraDescripcion(String platraDescripcion) {
        this.platraDescripcion = platraDescripcion;
    }
    public Date getPlatraFechaproceso() {
        return this.platraFechaproceso;
    }
    
    public void setPlatraFechaproceso(Date platraFechaproceso) {
        this.platraFechaproceso = platraFechaproceso;
    }
    public Set getEtapasTrabajoses() {
        return this.etapasTrabajoses;
    }
    
    public void setEtapasTrabajoses(Set etapasTrabajoses) {
        this.etapasTrabajoses = etapasTrabajoses;
    }




}


