package CobroCoactivo.Modelo;
// Generated 30/05/2018 02:16:05 PM by Hibernate Tools 4.3.1


import CobroCoactivo.Persistencia.CivEstadoPlanGenerales;
import CobroCoactivo.Persistencia.CivPlanGenerales;
import java.util.HashSet;
import java.util.Set;

/**
 * PlanGenerales generated by hbm2java
 */
public class PlanGenerales  implements java.io.Serializable {


     private int Id;
     private EstadoPlanGenerales estadoPlanGenerales = new EstadoPlanGenerales();
     private String Descripcion;
     private int Fechaproceso;

    public PlanGenerales() {
    }
    
    public PlanGenerales(CivPlanGenerales civPlanGenerales){
        this.Id = civPlanGenerales.getPlagenId().intValue();
       this.Descripcion = civPlanGenerales.getPlagenDescripcion();
       this.Fechaproceso = civPlanGenerales.getPlagenFechaproceso().intValue();
    }
    public PlanGenerales(CivPlanGenerales civPlanGenerales,CivEstadoPlanGenerales civEstadoPlanGenerales){
       this.Id = civPlanGenerales.getPlagenId().intValue();
       this.Descripcion = civPlanGenerales.getPlagenDescripcion();
       this.Fechaproceso = civPlanGenerales.getPlagenFechaproceso().intValue();
       this.estadoPlanGenerales = new EstadoPlanGenerales(civEstadoPlanGenerales);
    }
            
   
    public int getPlagenId() {
        return this.Id;
    }
    
    public void setPlagenId(int Id) {
        this.Id = Id;
    }
    public EstadoPlanGenerales getEstadoPlanGenerales() {
        return this.estadoPlanGenerales;
    }
    
    public void setEstadoPlanGenerales(EstadoPlanGenerales estadoPlanGenerales) {
        this.estadoPlanGenerales = estadoPlanGenerales;
    }
    public String getPlagenDescripcion() {
        return this.Descripcion;
    }
    
    public void setPlagenDescripcion(String Descripcion) {
        this.Descripcion = Descripcion;
    }
    public int getPlagenFechaproceso() {
        return this.Fechaproceso;
    }
    
    public void setPlagenFechaproceso(int Fechaproceso) {
        this.Fechaproceso = Fechaproceso;
    }




}


