package CobroCoactivo.Modelo;
// Generated 30/05/2018 02:16:05 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Recursos generated by hbm2java
 */
public class Recursos  implements java.io.Serializable {


     private BigDecimal recId;
     private TipoRecursos tipoRecursos;
     private Perfiles perfiles;
     private Modulos modulos;
     private EstadoRecursos estadoRecursos;
     private String recNombre;
     private String recDescripcion;
     private Date recFechaproceso;
     private String recCarperta;
     private Set confUsuRecs = new HashSet(0);

    public Recursos() {
    }

	
    public Recursos(BigDecimal recId, TipoRecursos tipoRecursos, Perfiles perfiles, Modulos modulos, EstadoRecursos estadoRecursos, String recNombre) {
        this.recId = recId;
        this.tipoRecursos = tipoRecursos;
        this.perfiles = perfiles;
        this.modulos = modulos;
        this.estadoRecursos = estadoRecursos;
        this.recNombre = recNombre;
    }
    public Recursos(BigDecimal recId, TipoRecursos tipoRecursos, Perfiles perfiles, Modulos modulos, EstadoRecursos estadoRecursos, String recNombre, String recDescripcion, Date recFechaproceso, String recCarperta, Set confUsuRecs) {
       this.recId = recId;
       this.tipoRecursos = tipoRecursos;
       this.perfiles = perfiles;
       this.modulos = modulos;
       this.estadoRecursos = estadoRecursos;
       this.recNombre = recNombre;
       this.recDescripcion = recDescripcion;
       this.recFechaproceso = recFechaproceso;
       this.recCarperta = recCarperta;
       this.confUsuRecs = confUsuRecs;
    }
   
    public BigDecimal getRecId() {
        return this.recId;
    }
    
    public void setRecId(BigDecimal recId) {
        this.recId = recId;
    }
    public TipoRecursos getTipoRecursos() {
        return this.tipoRecursos;
    }
    
    public void setTipoRecursos(TipoRecursos tipoRecursos) {
        this.tipoRecursos = tipoRecursos;
    }
    public Perfiles getPerfiles() {
        return this.perfiles;
    }
    
    public void setPerfiles(Perfiles perfiles) {
        this.perfiles = perfiles;
    }
    public Modulos getModulos() {
        return this.modulos;
    }
    
    public void setModulos(Modulos modulos) {
        this.modulos = modulos;
    }
    public EstadoRecursos getEstadoRecursos() {
        return this.estadoRecursos;
    }
    
    public void setEstadoRecursos(EstadoRecursos estadoRecursos) {
        this.estadoRecursos = estadoRecursos;
    }
    public String getRecNombre() {
        return this.recNombre;
    }
    
    public void setRecNombre(String recNombre) {
        this.recNombre = recNombre;
    }
    public String getRecDescripcion() {
        return this.recDescripcion;
    }
    
    public void setRecDescripcion(String recDescripcion) {
        this.recDescripcion = recDescripcion;
    }
    public Date getRecFechaproceso() {
        return this.recFechaproceso;
    }
    
    public void setRecFechaproceso(Date recFechaproceso) {
        this.recFechaproceso = recFechaproceso;
    }
    public String getRecCarperta() {
        return this.recCarperta;
    }
    
    public void setRecCarperta(String recCarperta) {
        this.recCarperta = recCarperta;
    }
    public Set getConfUsuRecs() {
        return this.confUsuRecs;
    }
    
    public void setConfUsuRecs(Set confUsuRecs) {
        this.confUsuRecs = confUsuRecs;
    }




}


