package CobroCoactivo.Modelo;
// Generated 30/05/2018 02:16:05 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * ReporteTrabajos generated by hbm2java
 */
public class ReporteTrabajos  implements java.io.Serializable {


     private BigDecimal reptraId;
     private EstadoReporteTrabajos estadoReporteTrabajos;
     private String reptraDescripcion;
     private Date reptraFechaproceso;
     private String reptraArchivo;
     private Set fasesTrabajoses = new HashSet(0);

    public ReporteTrabajos() {
    }

	
    public ReporteTrabajos(BigDecimal reptraId, EstadoReporteTrabajos estadoReporteTrabajos, String reptraDescripcion) {
        this.reptraId = reptraId;
        this.estadoReporteTrabajos = estadoReporteTrabajos;
        this.reptraDescripcion = reptraDescripcion;
    }
    public ReporteTrabajos(BigDecimal reptraId, EstadoReporteTrabajos estadoReporteTrabajos, String reptraDescripcion, Date reptraFechaproceso, String reptraArchivo, Set fasesTrabajoses) {
       this.reptraId = reptraId;
       this.estadoReporteTrabajos = estadoReporteTrabajos;
       this.reptraDescripcion = reptraDescripcion;
       this.reptraFechaproceso = reptraFechaproceso;
       this.reptraArchivo = reptraArchivo;
       this.fasesTrabajoses = fasesTrabajoses;
    }
   
    public BigDecimal getReptraId() {
        return this.reptraId;
    }
    
    public void setReptraId(BigDecimal reptraId) {
        this.reptraId = reptraId;
    }
    public EstadoReporteTrabajos getEstadoReporteTrabajos() {
        return this.estadoReporteTrabajos;
    }
    
    public void setEstadoReporteTrabajos(EstadoReporteTrabajos estadoReporteTrabajos) {
        this.estadoReporteTrabajos = estadoReporteTrabajos;
    }
    public String getReptraDescripcion() {
        return this.reptraDescripcion;
    }
    
    public void setReptraDescripcion(String reptraDescripcion) {
        this.reptraDescripcion = reptraDescripcion;
    }
    public Date getReptraFechaproceso() {
        return this.reptraFechaproceso;
    }
    
    public void setReptraFechaproceso(Date reptraFechaproceso) {
        this.reptraFechaproceso = reptraFechaproceso;
    }
    public String getReptraArchivo() {
        return this.reptraArchivo;
    }
    
    public void setReptraArchivo(String reptraArchivo) {
        this.reptraArchivo = reptraArchivo;
    }
    public Set getFasesTrabajoses() {
        return this.fasesTrabajoses;
    }
    
    public void setFasesTrabajoses(Set fasesTrabajoses) {
        this.fasesTrabajoses = fasesTrabajoses;
    }




}


