package CobroCoactivo.Modelo;
// Generated 30/05/2018 02:16:05 PM by Hibernate Tools 4.3.1

import CobroCoactivo.Persistencia.CivEstadoReporteTrabajos;
import CobroCoactivo.Persistencia.CivReporteTrabajos;
import java.util.Date;

/**
 * ReporteTrabajos generated by hbm2java
 */
public class ReporteTrabajos implements java.io.Serializable {

    private int Id;
    private EstadoReporteTrabajos estadoReporteTrabajos;
    private String Descripcion;
    private Date Fechaproceso;
    private String Archivo;

    public ReporteTrabajos() {
    }

    public ReporteTrabajos(CivReporteTrabajos civReporteTrabajos) {
        this.Id = civReporteTrabajos.getReptraId().intValue();
        this.Fechaproceso = civReporteTrabajos.getReptraFechaproceso();
        this.Descripcion = civReporteTrabajos.getReptraDescripcion();
        this.Archivo = civReporteTrabajos.getReptraArchivo();
    }

    public ReporteTrabajos(CivReporteTrabajos civReporteTrabajos, CivEstadoReporteTrabajos civEstadoReporteTrabajos) {
        this.Id = civReporteTrabajos.getReptraId().intValue();
        this.Fechaproceso = civReporteTrabajos.getReptraFechaproceso();
        this.Descripcion = civReporteTrabajos.getReptraDescripcion();
        this.Archivo = civReporteTrabajos.getReptraArchivo();
        this.estadoReporteTrabajos = new EstadoReporteTrabajos(civEstadoReporteTrabajos);

    }

    public int getReptraId() {
        return this.Id;
    }

    public void setReptraId(int Id) {
        this.Id = Id;
    }

    public EstadoReporteTrabajos getEstadoReporteTrabajos() {
        return this.estadoReporteTrabajos;
    }

    public void setEstadoReporteTrabajos(EstadoReporteTrabajos estadoReporteTrabajos) {
        this.estadoReporteTrabajos = estadoReporteTrabajos;
    }

    public String getReptraDescripcion() {
        return this.Descripcion;
    }

    public void setReptraDescripcion(String Descripcion) {
        this.Descripcion = Descripcion;
    }

    public Date getReptraFechaproceso() {
        return this.Fechaproceso;
    }

    public void setReptraFechaproceso(Date Fechaproceso) {
        this.Fechaproceso = Fechaproceso;
    }

    public String getReptraArchivo() {
        return this.Archivo;
    }

    public void setReptraArchivo(String Archivo) {
        this.Archivo = Archivo;
    }
}
