package CobroCoactivo.Modelo;
// Generated 30/05/2018 02:16:05 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * TipoConceptos generated by hbm2java
 */
public class TipoConceptos  implements java.io.Serializable {


     private BigDecimal tipconId;
     private String tipconDescripcion;
     private String tipconNombrecorto;
     private BigDecimal tipconCodigo;
     private Date tipconFechainicial;
     private Date tipconFechafinal;
     private Set conceptoses = new HashSet(0);

    public TipoConceptos() {
    }

	
    public TipoConceptos(BigDecimal tipconId, String tipconDescripcion) {
        this.tipconId = tipconId;
        this.tipconDescripcion = tipconDescripcion;
    }
    public TipoConceptos(BigDecimal tipconId, String tipconDescripcion, String tipconNombrecorto, BigDecimal tipconCodigo, Date tipconFechainicial, Date tipconFechafinal, Set conceptoses) {
       this.tipconId = tipconId;
       this.tipconDescripcion = tipconDescripcion;
       this.tipconNombrecorto = tipconNombrecorto;
       this.tipconCodigo = tipconCodigo;
       this.tipconFechainicial = tipconFechainicial;
       this.tipconFechafinal = tipconFechafinal;
       this.conceptoses = conceptoses;
    }
   
    public BigDecimal getTipconId() {
        return this.tipconId;
    }
    
    public void setTipconId(BigDecimal tipconId) {
        this.tipconId = tipconId;
    }
    public String getTipconDescripcion() {
        return this.tipconDescripcion;
    }
    
    public void setTipconDescripcion(String tipconDescripcion) {
        this.tipconDescripcion = tipconDescripcion;
    }
    public String getTipconNombrecorto() {
        return this.tipconNombrecorto;
    }
    
    public void setTipconNombrecorto(String tipconNombrecorto) {
        this.tipconNombrecorto = tipconNombrecorto;
    }
    public BigDecimal getTipconCodigo() {
        return this.tipconCodigo;
    }
    
    public void setTipconCodigo(BigDecimal tipconCodigo) {
        this.tipconCodigo = tipconCodigo;
    }
    public Date getTipconFechainicial() {
        return this.tipconFechainicial;
    }
    
    public void setTipconFechainicial(Date tipconFechainicial) {
        this.tipconFechainicial = tipconFechainicial;
    }
    public Date getTipconFechafinal() {
        return this.tipconFechafinal;
    }
    
    public void setTipconFechafinal(Date tipconFechafinal) {
        this.tipconFechafinal = tipconFechafinal;
    }
    public Set getConceptoses() {
        return this.conceptoses;
    }
    
    public void setConceptoses(Set conceptoses) {
        this.conceptoses = conceptoses;
    }




}


