package CobroCoactivo.Modelo;
// Generated 30/05/2018 02:16:05 PM by Hibernate Tools 4.3.1

import CobroCoactivo.Persistencia.CivTipoExpedientes;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * TipoExpedientes generated by hbm2java
 */
public class TipoExpedientes implements java.io.Serializable {

    private int Id;
    private String Descripcion;
    private String Nombrecorto;
    private int Codigo;
    private Date Fechainicial;
    private Date Fechafinal;
    private Set expedienteses = new HashSet(0);

    public TipoExpedientes() {
    }

    public TipoExpedientes(CivTipoExpedientes civTipoExpedientes) {
        this.Id = civTipoExpedientes.getTipexpId().intValue();
        this.Descripcion = civTipoExpedientes.getTipexpDescripcion();
        this.Nombrecorto = civTipoExpedientes.getTipexpNombrecorto();
        this.Codigo = civTipoExpedientes.getTipexpCodigo().intValue();
        this.Fechainicial = civTipoExpedientes.getTipexpFechainicial();
        this.Fechafinal = civTipoExpedientes.getTipexpFechafinal();
    }

    public int getTipexpId() {
        return this.Id;
    }

    public void setTipexpId(int Id) {
        this.Id = Id;
    }

    public String getTipexpDescripcion() {
        return this.Descripcion;
    }

    public void setTipexpDescripcion(String Descripcion) {
        this.Descripcion = Descripcion;
    }

    public String getTipexpNombrecorto() {
        return this.Nombrecorto;
    }

    public void setTipexpNombrecorto(String Nombrecorto) {
        this.Nombrecorto = Nombrecorto;
    }

    public int getTipexpCodigo() {
        return this.Codigo;
    }

    public void setTipexpCodigo(int Codigo) {
        this.Codigo = Codigo;
    }

    public Date getTipexpFechainicial() {
        return this.Fechainicial;
    }

    public void setTipexpFechainicial(Date Fechainicial) {
        this.Fechainicial = Fechainicial;
    }

    public Date getTipexpFechafinal() {
        return this.Fechafinal;
    }

    public void setTipexpFechafinal(Date Fechafinal) {
        this.Fechafinal = Fechafinal;
    }

    public Set getExpedienteses() {
        return this.expedienteses;
    }

    public void setExpedienteses(Set expedienteses) {
        this.expedienteses = expedienteses;
    }

}
