package CobroCoactivo.Modelo;
// Generated 30/05/2018 02:16:05 PM by Hibernate Tools 4.3.1


import CobroCoactivo.Persistencia.CivTipoDeudas;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * TipoDeudas generated by hbm2java
 */
public class TipoDeudas  implements java.io.Serializable {


     private int Id;
     private String Descripcion;
     private String Nombrecorto;
     private int Codigo;
     private Date Fechainicial;
     private Date Fechafinal;

    public TipoDeudas() {
    }

    public TipoDeudas(CivTipoDeudas civTipoDeudas) {
        this.Id = civTipoDeudas.getTipdeuId().intValue();
        this.Descripcion = civTipoDeudas.getTipdeuDescripcion();
        this.Nombrecorto = civTipoDeudas.getTipdeuNombrecorto();
        this.Codigo = civTipoDeudas.getTipdeuCodigo().intValue();
        this.Fechainicial = civTipoDeudas.getTipdeuFechainicial();
        this.Fechafinal = civTipoDeudas.getTipdeuFechafinal();
    }

	
    public TipoDeudas(int Id, String Descripcion) {
        this.Id = Id;
        this.Descripcion = Descripcion;
    }

    /**
     * @return the Id
     */
    public int getId() {
        return Id;
    }

    /**
     * @param Id the Id to set
     */
    public void setId(int Id) {
        this.Id = Id;
    }

    /**
     * @return the Descripcion
     */
    public String getDescripcion() {
        return Descripcion;
    }

    /**
     * @param Descripcion the Descripcion to set
     */
    public void setDescripcion(String Descripcion) {
        this.Descripcion = Descripcion;
    }

    /**
     * @return the Nombrecorto
     */
    public String getNombrecorto() {
        return Nombrecorto;
    }

    /**
     * @param Nombrecorto the Nombrecorto to set
     */
    public void setNombrecorto(String Nombrecorto) {
        this.Nombrecorto = Nombrecorto;
    }

    /**
     * @return the Codigo
     */
    public int getCodigo() {
        return Codigo;
    }

    /**
     * @param Codigo the Codigo to set
     */
    public void setCodigo(int Codigo) {
        this.Codigo = Codigo;
    }

    /**
     * @return the Fechainicial
     */
    public Date getFechainicial() {
        return Fechainicial;
    }

    /**
     * @param Fechainicial the Fechainicial to set
     */
    public void setFechainicial(Date Fechainicial) {
        this.Fechainicial = Fechainicial;
    }

    /**
     * @return the Fechafinal
     */
    public Date getFechafinal() {
        return Fechafinal;
    }

    /**
     * @param Fechafinal the Fechafinal to set
     */
    public void setFechafinal(Date Fechafinal) {
        this.Fechafinal = Fechafinal;
    }
   
}


