package CobroCoactivo.Modelo;
// Generated 30/05/2018 02:16:05 PM by Hibernate Tools 4.3.1


import CobroCoactivo.Persistencia.CivTipoRecursos;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * TipoRecursos generated by hbm2java
 */
public class TipoRecursos  implements java.io.Serializable {


     private int id;
     private String descripcion;
     private String nombrecorto;
     private Date fechainicial;
     private Date fechafinal;
     private int codigo;

    public TipoRecursos() {
    }

    public TipoRecursos(CivTipoRecursos civTipoRecursos) {
        this.id = civTipoRecursos.getTiprecId().intValue();
        this.descripcion = civTipoRecursos.getTiprecDescripcion();
        this.nombrecorto = civTipoRecursos.getTiprecNombrecorto();
        this.fechainicial = civTipoRecursos.getTiprecFechainicial();
        this.fechafinal = civTipoRecursos.getTiprecFechafinal();
        this.codigo = civTipoRecursos.getTiprecCodigo().intValue();
    }

    /**
     * @return the id
     */
    public int getId() {
        return id;
    }

    /**
     * @param id the id to set
     */
    public void setId(int id) {
        this.id = id;
    }

    /**
     * @return the descripcion
     */
    public String getDescripcion() {
        return descripcion;
    }

    /**
     * @param descripcion the descripcion to set
     */
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    /**
     * @return the nombrecorto
     */
    public String getNombrecorto() {
        return nombrecorto;
    }

    /**
     * @param nombrecorto the nombrecorto to set
     */
    public void setNombrecorto(String nombrecorto) {
        this.nombrecorto = nombrecorto;
    }

    /**
     * @return the fechainicial
     */
    public Date getFechainicial() {
        return fechainicial;
    }

    /**
     * @param fechainicial the fechainicial to set
     */
    public void setFechainicial(Date fechainicial) {
        this.fechainicial = fechainicial;
    }

    /**
     * @return the fechafinal
     */
    public Date getFechafinal() {
        return fechafinal;
    }

    /**
     * @param fechafinal the fechafinal to set
     */
    public void setFechafinal(Date fechafinal) {
        this.fechafinal = fechafinal;
    }

    /**
     * @return the codigo
     */
    public int getCodigo() {
        return codigo;
    }

    /**
     * @param codigo the codigo to set
     */
    public void setCodigo(int codigo) {
        this.codigo = codigo;
    }


   


}


