package CobroCoactivo.Modelo;
// Generated 30/05/2018 02:16:05 PM by Hibernate Tools 4.3.1

import CobroCoactivo.Persistencia.CivTipoDocumentos;
import java.util.Date;

/**
 * TipoDocumentos generated by hbm2java
 */
public class TipoDocumentos implements java.io.Serializable {

    private int Id;
    private String Descripcion;
    private String Nombrecorto;
    private Date Fechainicial;
    private Date Fechafinal;
    private int Codigo;

    public TipoDocumentos() {
    }

    public TipoDocumentos(CivTipoDocumentos civTipoDocumentos) {
        this.Id = civTipoDocumentos.getTipdocId().intValue();
        this.Descripcion = civTipoDocumentos.getTipdocDescripcion();
        this.Nombrecorto = civTipoDocumentos.getTipdocNombrecorto();
        this.Fechainicial = civTipoDocumentos.getTipdocFechainicial();
        this.Fechafinal = civTipoDocumentos.getTipdocFechafinal();
        this.Codigo = civTipoDocumentos.getTipdocCodigo().intValue();
    }

    /**
     * @return the Id
     */
    public int getId() {
        return Id;
    }

    /**
     * @param Id the Id to set
     */
    public void setId(int Id) {
        this.Id = Id;
    }

    /**
     * @return the Descripcion
     */
    public String getDescripcion() {
        return Descripcion;
    }

    /**
     * @param Descripcion the Descripcion to set
     */
    public void setDescripcion(String Descripcion) {
        this.Descripcion = Descripcion;
    }

    /**
     * @return the Nombrecorto
     */
    public String getNombrecorto() {
        return Nombrecorto;
    }

    /**
     * @param Nombrecorto the Nombrecorto to set
     */
    public void setNombrecorto(String Nombrecorto) {
        this.Nombrecorto = Nombrecorto;
    }

    /**
     * @return the Fechainicial
     */
    public Date getFechainicial() {
        return Fechainicial;
    }

    /**
     * @param Fechainicial the Fechainicial to set
     */
    public void setFechainicial(Date Fechainicial) {
        this.Fechainicial = Fechainicial;
    }

    /**
     * @return the Fechafinal
     */
    public Date getFechafinal() {
        return Fechafinal;
    }

    /**
     * @param Fechafinal the Fechafinal to set
     */
    public void setFechafinal(Date Fechafinal) {
        this.Fechafinal = Fechafinal;
    }

    /**
     * @return the Codigo
     */
    public int getCodigo() {
        return Codigo;
    }

    /**
     * @param Codigo the Codigo to set
     */
    public void setCodigo(int Codigo) {
        this.Codigo = Codigo;
    }

}
