package CobroCoactivo.Modelo;
// Generated 30/05/2018 02:16:05 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * TipoExpedientes generated by hbm2java
 */
public class TipoExpedientes  implements java.io.Serializable {


     private BigDecimal tipexpId;
     private String tipexpDescripcion;
     private String tipexpNombrecorto;
     private BigDecimal tipexpCodigo;
     private Date tipexpFechainicial;
     private Date tipexpFechafinal;
     private Set expedienteses = new HashSet(0);

    public TipoExpedientes() {
    }

	
    public TipoExpedientes(BigDecimal tipexpId, String tipexpDescripcion) {
        this.tipexpId = tipexpId;
        this.tipexpDescripcion = tipexpDescripcion;
    }
    public TipoExpedientes(BigDecimal tipexpId, String tipexpDescripcion, String tipexpNombrecorto, BigDecimal tipexpCodigo, Date tipexpFechainicial, Date tipexpFechafinal, Set expedienteses) {
       this.tipexpId = tipexpId;
       this.tipexpDescripcion = tipexpDescripcion;
       this.tipexpNombrecorto = tipexpNombrecorto;
       this.tipexpCodigo = tipexpCodigo;
       this.tipexpFechainicial = tipexpFechainicial;
       this.tipexpFechafinal = tipexpFechafinal;
       this.expedienteses = expedienteses;
    }
   
    public BigDecimal getTipexpId() {
        return this.tipexpId;
    }
    
    public void setTipexpId(BigDecimal tipexpId) {
        this.tipexpId = tipexpId;
    }
    public String getTipexpDescripcion() {
        return this.tipexpDescripcion;
    }
    
    public void setTipexpDescripcion(String tipexpDescripcion) {
        this.tipexpDescripcion = tipexpDescripcion;
    }
    public String getTipexpNombrecorto() {
        return this.tipexpNombrecorto;
    }
    
    public void setTipexpNombrecorto(String tipexpNombrecorto) {
        this.tipexpNombrecorto = tipexpNombrecorto;
    }
    public BigDecimal getTipexpCodigo() {
        return this.tipexpCodigo;
    }
    
    public void setTipexpCodigo(BigDecimal tipexpCodigo) {
        this.tipexpCodigo = tipexpCodigo;
    }
    public Date getTipexpFechainicial() {
        return this.tipexpFechainicial;
    }
    
    public void setTipexpFechainicial(Date tipexpFechainicial) {
        this.tipexpFechainicial = tipexpFechainicial;
    }
    public Date getTipexpFechafinal() {
        return this.tipexpFechafinal;
    }
    
    public void setTipexpFechafinal(Date tipexpFechafinal) {
        this.tipexpFechafinal = tipexpFechafinal;
    }
    public Set getExpedienteses() {
        return this.expedienteses;
    }
    
    public void setExpedienteses(Set expedienteses) {
        this.expedienteses = expedienteses;
    }




}


